### ISSUE TITLE
Unable to shade JavaCord using Maven and Spigot

### ISSUE THREAD

**Issue by TheSimonCraft** [Javacord/Javacord#1025]
I recently started coding a Discord bot connecting to a Minecraft plugin (using Maven and Spigot). I imported the dependency in the pom.xml file, but my plugin seems to be unable to shade it.

So when I try to install it (using maven install), I'm getting following errors:

> [INFO] Skipping pom dependency org.javacord:javacord:pom:3.4.0 in the shaded jar.
> [WARNING] Life-Steal-1.3-DEV.jar, bcprov-jdk15on-1.59.jar, jackson-annotations-2.9.0.jar, jackson-core-2.9.3.jar, jackson-databind-2.9.3.jar, javacord-api-3.4.0.jar, javacord-core-3.4.0.jar, log4j-api-2.17.1.jar, logging-interceptor-3.9.1.jar, nv-websocket-client-2.6.jar, okhttp-3.9.1.jar, okio-1.13.0.jar, vavr-0.10.1.jar, vavr-match-0.10.1.jar, xsalsa20poly1305-0.10.1.jar define 1 overlapping resource: 
> [WARNING]   - META-INF/MANIFEST.MF
> [WARNING] javacord-api-3.4.0.jar, javacord-core-3.4.0.jar, log4j-api-2.17.1.jar define 1 overlapping classes: 
> [WARNING]   - META-INF.versions.9.module-info
> [WARNING] javacord-core-3.4.0.jar, log4j-api-2.17.1.jar define 1 overlapping resource: 
> [WARNING]   - META-INF/services/org.apache.logging.log4j.util.PropertySource
> [WARNING] jackson-annotations-2.9.0.jar, jackson-core-2.9.3.jar, jackson-databind-2.9.3.jar, log4j-api-2.17.1.jar define 1 overlapping resource: 
> [WARNING]   - META-INF/LICENSE
> [WARNING] jackson-core-2.9.3.jar, jackson-databind-2.9.3.jar, log4j-api-2.17.1.jar define 1 overlapping resource: 
> [WARNING]   - META-INF/NOTICE
> [WARNING] maven-shade-plugin has detected that some class files are
> [WARNING] present in two or more JARs. When this happens, only one
> [WARNING] single version of the class is copied to the uber jar.
> [WARNING] Usually this is not harmful and you can skip these warnings,
> [WARNING] otherwise try to manually exclude artifacts based on
> [WARNING] mvn dependency:tree -Ddetail=true and the above output.
> [WARNING] See http://maven.apache.org/plugins/maven-shade-plugin/

Also, when I try to run my plugin on a local server, it results in following error:

> [22:17:21] [Server thread/ERROR]: Error occurred while enabling Life-Steal v1.3-DEV (Is it up to date?)
> java.lang.NoClassDefFoundError: org/javacord/api/listener/GloballyAttachableListener
>         at at.thesimoncraft.lifesteal.Main.onEnable(Main.java:77) ~[?:?]
>         at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
>         at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
>         at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
>         at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:517) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3453-Spigot-ffceeae-64db512]
>         at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:431) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3453-Spigot-ffceeae-64db512]
>         at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:233) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3453-Spigot-ffceeae-64db512]
>         at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1007) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3453-Spigot-ffceeae-64db512]
>         at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3453-Spigot-ffceeae-64db512]
>         at java.lang.Thread.run(Thread.java:833) [?:?]
> Caused by: java.lang.ClassNotFoundException: org.javacord.api.listener.GloballyAttachableListener
>         at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:147) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
>         at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
>         ... 10 more

My pom.xml:

`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>at.thesimoncraft</groupId>
    <artifactId>Life-Steal</artifactId>
    <version>1.3-DEV</version>
    <packaging>jar</packaging>

    <name>Life-Steal</name>

    <description>This is a custom life-steal plugin by TheSimonCraft!</description>
    <properties>
        <java.version>1.8</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.2.4</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <createDependencyReducedPom>false</createDependencyReducedPom>
                            <outputDirectory>(My Output Directory)</outputDirectory>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
    </build>

    <repositories>
        <repository>
            <id>spigotmc-repo</id>
            <url>https://hub.spigotmc.org/nexus/content/repositories/snapshots/</url>
        </repository>
        <repository>
            <id>sonatype</id>
            <url>https://oss.sonatype.org/content/groups/public/</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>org.spigotmc</groupId>
            <artifactId>spigot-api</artifactId>
            <version>1.18.1-R0.1-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.javacord</groupId>
            <artifactId>javacord</artifactId>
            <version>3.4.0</version>
            <type>pom</type>
        </dependency>
    </dependencies>
</project>
`

It kind of cuts away the top section of the pom.xml file, so if you need it, just tell me...

Thank you for helping me in advance!

**Comment by Vampire** [comment]
Besides that it is called Javacord, not JavaCord, I don't see any errors in what you sent, just a bunch of warnings about duplicate files which is expected if you build bad-practice fat jars like Minecraft kind of forces you to.

Why the class is not found? No idea, look in your jar whether it is available, I'd guess yes from the first output you sent and if so, maybe debug your project to find out what is going wrong. Others were able to build Bukkit plugins with Javacord included. It's not uncommon that there are problems with fat jars as this is a rape of your dependencies and your are not using what library authors provide you. ;-)

I'm closing this issue, as it is not a Javacord problem, but more a question how to make Bukkit happy. You might get further help if you need it on the Discord server though.
