### ISSUE TITLE
ApplicationCommandUpdater's Perms v2 methods invalid return type.

### ISSUE THREAD

**Issue by ShindouMihou** [Javacord/Javacord#1026]
`SlashCommandUpdater` a.k.a the `ApplicationCommandUpdater` has a fairly critical issue addressed in https://github.com/Javacord/Javacord/commit/d05f74c6ccb3c93b92b3f6284e2194f102ae541a#r76468200 wherein the return type which was expected to be of `B` (or the builder) isn't returned but is instead returning the final result type which shouldn't be castable with `this`.

![image](https://user-images.githubusercontent.com/69381903/174495049-7eac0b1f-1052-4fdb-ad21-49700138ce1b.png)
![image](https://user-images.githubusercontent.com/69381903/174495094-4e6f0678-ad26-4029-8f4f-87726a54bc02.png)

This applies on all new methods in `ApplicationCommandUpdater`.

**Comment by KILLEliteMaste** [comment]
Yeah, this was a simple copy paste mistake. Going to fix this real quick
