### ISSUE TITLE
Threads don't get removed from cache if the parent channel is deleted, causing AssertionErrors

### ISSUE THREAD

**Issue by wasdennnoch** [Javacord/Javacord#1028]
When you create a thread (tested with a public one, most likely affects private threads too) in a channel and then later delete said channel, the thread is not removed from Javacord's channel cache. This causes the channel cache to contain threads without a parent channel (since the deleted parent correctly gets removed from cache) - which again introduces the dreaded `AssertionError: Thread has no parent channel` when trying to access that server's channel list through methods such as `Server.getChannels()` :D

I think this is because there is no special handling for threads in the `ChannelDeleteHandler`, and Discord doesn't send `THREAD_DELETE` packets if the parent channel is deleted. As mentioned in the Discord documentation:

> When a client loses access to a channel, the gateway does not send them a `Thread Delete` event or any equivalent. They will still receive _an_ event when this happens, it just will not be a thread-specific event.

I have not tested whether this also leaves behind stray ThreadChannel instances in other caches such as the global channel cache, and whether that also happens when you delete the server as opposed to just the channel. But those are things that came to my mind which have to be looked out for.

This was tested using a mostly up-to-date Javacord version at f0171112064a48b60ff90bdb92a326f112366274.

In the same go, I suggest exposing the internal function `getUnorderedChannels()`, for cases where you want to access the channel list but don't care about it being sorted, to save some performance by not needlessly sorting the list.

Demonstration:

https://user-images.githubusercontent.com/10065021/174498712-0e77a29b-a059-4c33-830e-f812cfd56cfd.mp4

**Comment by KILLEliteMaste** [comment]
> I have not tested whether this also leaves behind stray ThreadChannel instances in other caches such as the global channel cache

There are no other caches, we have just one cache where the channels are stored.

> also happens when you delete the server as opposed to just the channel

This case is already covered as we remove all channels that belong to this server.

This should be a pretty simple fix where we just have to remove the threads in i.e. the `cleanup` method channels can implement. I am not sure what's the best way to do this, either as said in the cleanup method or just doing this always when we receive a `CHANNEL_DELETE` event. The latter will be future proof in cases where Discord suddenly decides i.e. Categories can also have threads. In this case doing it the cleanup way would still break this method.
