### ISSUE TITLE
Improve Release Workflow

### ISSUE THREAD

**Issue by Bastian** [Javacord/Javacord#1033]
There are some small issues in the new release workflow:

- The release draft has the title `Release <x>.<y>.<z>` instead of `v<x>.<y>.<z>`
- The release workflow fails to push a commit to master that appends the `-SNAPSHOT` suffix because the branch is protected. => Let the GitHub Action create a PR instead (and maybe auto-merge it)
- Gradle should automatically close and release the staging artifact in Nexus (so I don't have to do it manually everytime)

**Comment by shubhwip** [comment]
If no one has picked it up. Can i work on it ?

**Comment by Bastian** [comment]
Sure, go for it 👍
