### ISSUE TITLE
Ephermal message reply

### ISSUE THREAD

**Issue by itskekoff** [Javacord/Javacord#1068]
i have a code that sends message with Button, users click and bot sends message without "Only you can see this".
How i can send "Only you can see this" message in ButtonClickEvent?

**Comment by zFlxw** [comment]
As this is not really related to the development of Javacord, please visit the Javacord Discord server to get help with your problem.

**Comment by Saladoc** [comment]
You're looking for [InteractionMessageBuilderBase#setFlags](https://javadoc.io/doc/org.javacord/javacord-api/latest/org/javacord/api/interaction/callback/InteractionMessageBuilderBase.html#setFlags(java.util.EnumSet)). You can set the EPHEMERAL flag there. 

If you're looking for help with Javacord, please find us at [our Discord Server](https://discord.gg/javacord), check the [wiki](https://wiki.javacord.org) or the [javadocs](https://docs.javacord.org) as you'll find it much easier and quicker to get help there. Usually only development related topics are taken to the github issues.
