### ISSUE TITLE
Support descriptions of message attachments

### ISSUE THREAD

**Issue by Saladoc** [Javacord/Javacord#1069]
[Message Attachments](https://discord.com/developers/docs/resources/channel#attachment-object) may have a description attribute.

This should be supported in our `MessageAttachment`s.

**Comment by shubhrjain** [comment]
Hello @Saladoc Can I pick this issue as I am first time open source contributor ?

**Comment by Saladoc** [comment]
Go ahead, open a PR. If you need help, find us on the linked discord server.
