### ISSUE TITLE
Add message interaction objects

### ISSUE THREAD

**Issue by KILLEliteMaste** [Javacord/Javacord#1075]
It seems like we do not currently support message interaction objects 
> This is sent on the [message object](https://discord.com/developers/docs/resources/channel#message-object) when the message is a response to an Interaction without an existing message.

https://discord.com/developers/docs/change-log#add-subcommand-groups-and-subcommands-to-message-interaction-objects
https://discord.com/developers/docs/interactions/receiving-and-responding#message-interaction-object

**Comment by AhmedA1559** [comment]
Can I be assigned this?

**Comment by KILLEliteMaste** [comment]
Sure :)
