### ISSUE TITLE
Add `app_permissions` field to interactions

### ISSUE THREAD

**Issue by KILLEliteMaste** [Javacord/Javacord#1076]
https://discord.com/developers/docs/change-log#calculated-permissions-in-interaction-payloads
https://discord.com/developers/docs/interactions/receiving-and-responding#interaction-object

**Comment by RealYusufIsmail** [comment]
shall i add this in api 10 update

**Comment by KILLEliteMaste** [comment]
Non, iIt is not required to upgrade to gateway v10, so it belongs to it's own PR
