### ISSUE TITLE
Bring the Server object and its fields up to date

### ISSUE THREAD

**Issue by KILLEliteMaste** [Javacord/Javacord#1087]
Missing fields:
* `premium_progress_bar_enabled`
* `welcome_screen`
* `max_video_channel_users`
* `max_members`
* `max_presences`
* `widget_channel_id`
* `widget_enabled`

ServerFeatures enum is outdated:
https://discord.com/developers/docs/resources/guild#guild-object-guild-features

Add missing System Channel Flags
https://discord.com/developers/docs/resources/guild#guild-object-system-channel-flags

**Comment by shubhwip** [comment]
Will take this.
