### ISSUE TITLE
Add missing fields to the Thread Metadata

### ISSUE THREAD

**Issue by KILLEliteMaste** [Javacord/Javacord#1092]
Missing fields:
* `invitable`
* `create_timestamp`

Furthermore the meta data fields should be moved to a new ThreadMetadata object
https://discord.com/developers/docs/resources/channel#thread-metadata-object-thread-metadata-structure

**Comment by RealYusufIsmail** [comment]
will also do this

**Comment by RealYusufIsmail** [comment]
Can i just do it in this pr https://github.com/Javacord/Javacord/pull/1089 since it is similar will change the title

**Comment by KILLEliteMaste** [comment]
How is this similar? The linked PR changes the message while this issue is about adjusting the ServerThreadChannel

**Comment by RealYusufIsmail** [comment]
ok
