### ISSUE TITLE
Add Guild Scheduled Event

### ISSUE THREAD

**Issue by RealYusufIsmail** [Javacord/Javacord#1097]
https://discord.com/developers/docs/change-log#nov-23-2021

**Comment by RealYusufIsmail** [comment]
Will work on this

**Comment by AhmedA1559** [comment]
Hi Yusuf, 
I've begun working on this as of yesterday (#946) but I can merge my changes into your branch.

**Comment by RealYusufIsmail** [comment]
yeah thats fine

**Comment by RealYusufIsmail** [comment]
> Hi Yusuf, I've begun working on this as of yesterday (#946) but I can merge my changes into your branch.

Its fine i will close my pr. You can work on it

**Comment by AhmedA1559** [comment]
> or you can take over the pr. I can work on some parts of it if you want

I can just do some parts of it and PR it to your fork if that's fine with you. We could split up the work (like implementing the Websocket Updates) between each other.

**Comment by RealYusufIsmail** [comment]
> > or you can take over the pr. I can work on some parts of it if you want
> 
> I can just do some parts of it and PR it to your fork if that's fine with you. We could split up the work (like implementing the Websocket Updates) between each other.

yeah thats fine. Just let me know on what parts to work on

**Comment by RealYusufIsmail** [comment]
@AhmedA1559 I am no longer interested on working on this, if you are willing can you take over. I will close my pr.
