### ISSUE TITLE
Respond with modal to a modal

### ISSUE THREAD

**Issue by Alexiscomete** [Javacord/Javacord#1132]
**My problem :**

I have more than 4 text inputs so I done 2 modals, one after the other. But we can't respond to a modal by a modal.

**Error :**

```
java.lang.UnsupportedOperationException: This method is not supported by this interaction
        at org.javacord.core.interaction.ModalInteractionImpl.respondWithModal(ModalInteractionImpl.java:62)
        at org.javacord.api.interaction.InteractionBase.respondWithModal(InteractionBase.java:74)
```

**How to solve it :**

Remove the "respond with modal" method from ModalSubmitEvent

(Sorry if it's duplicated, I check the issues, pr and version before so I think it's not)

**Comment by Alexiscomete** [comment]
My code : 

```kotlin
addCity.buttonInteraction.respondWithModal(...) // value-parameter addCity: ButtonClickEvent

modalManager.add(id) { modalPart1 -> // value-parameter modalPart1: ModalSubmitEvent
    // ...

    modalPart1.modalInteraction.respondWithModal(...)
    
    // ...
    
    
}

```

**Comment by KILLEliteMaste** [comment]
To my current knowledge it is not possible to respond with a modal to a modal. Hence it throws an error. Iirc they also do not plan to support this response to this interaction but instead they may try to find a different solution.

**Comment by Alexiscomete** [comment]
> To my current knowledge it is not possible to respond with a modal to a modal
yes, I change my code
> they also do not plan to support this response to this interaction but instead they may try to find a different solution.
👍 I only suggest to remove the implementation of the fonction

**Comment by KILLEliteMaste** [comment]
But this will not remove it due to inheritance and it will just unveil the respond method that actually performs a request. There is already an issue #1041 which mentions this problem.
