### ISSUE TITLE
Delete ephemeral and followup messages

### ISSUE THREAD

**Issue by KILLEliteMaste** [Javacord/Javacord#1160]
### What feature are you proposing?

Add new methods do delete ephemeral and followup messages

### Do you have any additional material for your feature proposal?

Changelog: https://discord.com/developers/docs/change-log#delete-ephemeral-messages

**Comment by RealYusufIsmail** [comment]
Will see if I can do this one

**Comment by RealYusufIsmail** [comment]
where would this be added

**Comment by RealYusufIsmail** [comment]
its already been added
<img width="879" alt="Screenshot 2022-10-22 at 09 41 53" src="https://user-images.githubusercontent.com/67903886/197330013-50051fe1-4d10-4b01-a93f-0b116f37327f.png">
<img width="829" alt="Screenshot 2022-10-22 at 09 42 01" src="https://user-images.githubusercontent.com/67903886/197330019-3a5f98c1-ec71-40fe-8176-337e374b7a79.png">
