### ISSUE TITLE
Wrong relative links in readme

### ISSUE THREAD

**Issue by Saladoc** [Javacord/Javacord#1174]
### Javacord version

not applicable

### What is expected?

Links in the [contributing section](https://github.com/Javacord/Javacord#-contributing) of the readme are leading to their correct targets

### What is actually happening?

Links in the contributing section of the readme are leading to a 404 error page.

### Any additional comments?

The links are written relative to `.github/README_template.md`, but parsed relatively to `README.md`.

All links in the readme are to be checked for correctness and fixed, if necessary.

**Comment by haseeb-xd** [comment]
I'll work on this issue, assign it to me

**Comment by haseeb-xd** [comment]
adding a commit for another fix
