### ISSUE TITLE
Slash Commands issue

### ISSUE THREAD

**Issue by cmclient** [Javacord/Javacord#1241]
### Javacord version

3.8.0

### Steps to reproduce

Create any slash command.

SlashCommand.with("help", "List of all commands")
                .createGlobal(BotApplication.getInstance().getApi())
                .join()

### What is expected?

Working normally.

### What is actually happening?

While using SlashCommands the bot is loading very long time, using 100% cpu and high amount of RAM.

**Comment by felldo** [comment]
I cannot reproduce this issue. Are you sure this piece of code causes the high CPU usage? Maybe your hardware is just too weak, or another part of your code causes this issue.
If you are sure that this is causing your issue, please create a simple, minimal working example that reproduces your problem.

**Comment by cmclient** [comment]
Ryzen 9 5950X is weak?
im sure that creating the slash command is the issue, tried java 11 and 16.
and bot after while creating the command use 2GB of ram.
without slash command everything works fine.
i have log "loading commands..." just before creating commands and issues starts right after this

**Comment by felldo** [comment]
> Ryzen 9 5950X is weak?

This was just an assumption, I don't know what hardware you are running your bot on.

The first thing you can try is changing your code to
```java
SlashCommand.with("help", "List of all commands")
.createGlobal(BotApplication.getInstance().getApi())
.exceptionally(ExceptionLogger.get())
.join()
```
So you actually get exceptions that discord may throw.
After that, you really should provide a complete minimal reproducible example that I can try.

**Comment by cmclient** [comment]
I created minimal example bot to verify it, and it happen when i have +3 commands.
Here is code to reproduce:

`package pl.cmclient;

import org.javacord.api.DiscordApi;
import org.javacord.api.DiscordApiBuilder;
import org.javacord.api.entity.permission.PermissionType;
import org.javacord.api.interaction.SlashCommand;
import org.javacord.api.interaction.SlashCommandOption;
import org.javacord.api.interaction.SlashCommandOptionType;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.Collections;
import java.util.List;

public class TestApp {

    public static void main(String[] args) {
        Logger logger = LoggerFactory.getLogger(TestApp.class);
        DiscordApi api = new DiscordApiBuilder()
                .setToken("OTE5MjQyMTMyNDc5NDIyNTQ0.GT8TtI.YPd9la999S_vG85lYLA2Lhd_sbnjQQpW5VOdkE")
                .setAllIntents()
                .login()
                .join();

        logger.info("Loading commands...");
        SlashCommand.with("help", "List of all commands")
                .createGlobal(api)
                .join();
        SlashCommand.with("ping", "Response time from Discord Gateway")
                .createGlobal(api)
                .join();
        SlashCommand.with("userinfo", "Info about player account",
                        Collections.singletonList(
                                SlashCommandOption.create(SlashCommandOptionType.STRING, "name", "Player name", true)))
                .createGlobal(api)
                .join();
        SlashCommand.with("test", "Test command")
                .createGlobal(api)
                .join();
        SlashCommand.with("clear", "Purge the chat",
                        Collections.singletonList(
                                SlashCommandOption.create(SlashCommandOptionType.LONG, "amount", "Amount of messages to purge", true)))
                .setDefaultEnabledForPermissions(PermissionType.MANAGE_MESSAGES)
                .setEnabledInDms(false)
                .createGlobal(api)
                .join();
        SlashCommand.with("ban", "Ban an user",
                        List.of(
                                SlashCommandOption.create(SlashCommandOptionType.USER, "user", "User that you want to ban", true),
                                SlashCommandOption.create(SlashCommandOptionType.STRING, "reason", "Reason of ban"),
                                SlashCommandOption.create(SlashCommandOptionType.LONG, "delete", "Delete messages from x days")))
                .setDefaultEnabledForPermissions(PermissionType.MANAGE_MESSAGES)
                .setEnabledInDms(false)
                .createGlobal(api)
                .join();
        SlashCommand.with("kick", "Kick an user",
                        List.of(
                                SlashCommandOption.create(SlashCommandOptionType.USER, "user", "User that you want to kick", true),
                                SlashCommandOption.create(SlashCommandOptionType.STRING, "reason", "Reason of kick")))
                .setDefaultEnabledForPermissions(PermissionType.MANAGE_MESSAGES)
                .setEnabledInDms(false)
                .createGlobal(api)
                .join();
        SlashCommand.with("embed", "Send message in a embed",
                        List.of(
                                SlashCommandOption.create(SlashCommandOptionType.STRING, "message", "Message (seperate title from description with |, for new line use \\n)", true)))
                .setDefaultEnabledForPermissions(PermissionType.MANAGE_MESSAGES)
                .createGlobal(api)
                .join();
        SlashCommand.with("pool", "Create a yes/no pool",
                        List.of(
                                SlashCommandOption.create(SlashCommandOptionType.STRING, "message", "Message (seperate title from description with |, for new line use \\n)", true)))
                .setDefaultEnabledForPermissions(PermissionType.MANAGE_MESSAGES)
                .createGlobal(api)
                .join();
        logger.info("Complete");
    }
}
`

**Comment by felldo** [comment]
Please regenerate your token, it is still visible in the edit history.

I tried your code and everything is working as intended, so Javacord does not seem to be an issue. Depending on where you see your RAM usage, it may also be consumed by your IDE. For me, IntelliJ IDEA likes to take up to 12 GB without doing anything. 
Another thing you could try is using the [snaphsot version](https://javacord.org/wiki/getting-started/download-installation.html) which I am currently using. After that, I am out of ideas regarding issues with Javacord.

**Comment by Saladoc** [comment]
I also could not reproduce the behavior you described, using Javacord 3.8.0 and Java 11. 

Side note: Registration of the Commands did take 15+ seconds when I tried it - using [`DiscordApi#bulkOverwriteGlobalApplicationCommands`](https://javadoc.io/doc/org.javacord/javacord-api/latest/org/javacord/api/DiscordApi.html) instead took less than half a second.

**Comment by feddevanderlist** [comment]
> I created minimal example bot to verify it, and it happen when i have +3 commands. Here is code to reproduce:
> 
> ```java
> package pl.cmclient;
> 
> import org.javacord.api.DiscordApi;
> import org.javacord.api.DiscordApiBuilder;
> import org.javacord.api.entity.permission.PermissionType;
> import org.javacord.api.interaction.SlashCommand;
> import org.javacord.api.interaction.SlashCommandOption;
> import org.javacord.api.interaction.SlashCommandOptionType;
> import org.slf4j.Logger;
> import org.slf4j.LoggerFactory;
> 
> import java.util.Collections;
> import java.util.List;
> 
> public class TestApp {
> 
>     public static void main(String[] args) {
>         Logger logger = LoggerFactory.getLogger(TestApp.class);
>         DiscordApi api = new DiscordApiBuilder()
>                 .setToken("xxx")
>                 .setAllIntents()
>                 .login()
>                 .join();
> 
>         logger.info("Loading commands...");
>         SlashCommand.with("help", "List of all commands")
>                 .createGlobal(api)
>                 .join();
>         SlashCommand.with("ping", "Response time from Discord Gateway")
>                 .createGlobal(api)
>                 .join();
>         SlashCommand.with("userinfo", "Info about player account",
>                         Collections.singletonList(
>                                 SlashCommandOption.create(SlashCommandOptionType.STRING, "name", "Player name", true)))
>                 .createGlobal(api)
>                 .join();
>         SlashCommand.with("test", "Test command")
>                 .createGlobal(api)
>                 .join();
>         SlashCommand.with("clear", "Purge the chat",
>                         Collections.singletonList(
>                                 SlashCommandOption.create(SlashCommandOptionType.LONG, "amount", "Amount of messages to purge", true)))
>                 .setDefaultEnabledForPermissions(PermissionType.MANAGE_MESSAGES)
>                 .setEnabledInDms(false)
>                 .createGlobal(api)
>                 .join();
>         SlashCommand.with("ban", "Ban an user",
>                         List.of(
>                                 SlashCommandOption.create(SlashCommandOptionType.USER, "user", "User that you want to ban", true),
>                                 SlashCommandOption.create(SlashCommandOptionType.STRING, "reason", "Reason of ban"),
>                                 SlashCommandOption.create(SlashCommandOptionType.LONG, "delete", "Delete messages from x days")))
>                 .setDefaultEnabledForPermissions(PermissionType.MANAGE_MESSAGES)
>                 .setEnabledInDms(false)
>                 .createGlobal(api)
>                 .join();
>         SlashCommand.with("kick", "Kick an user",
>                         List.of(
>                                 SlashCommandOption.create(SlashCommandOptionType.USER, "user", "User that you want to kick", true),
>                                 SlashCommandOption.create(SlashCommandOptionType.STRING, "reason", "Reason of kick")))
>                 .setDefaultEnabledForPermissions(PermissionType.MANAGE_MESSAGES)
>                 .setEnabledInDms(false)
>                 .createGlobal(api)
>                 .join();
>         SlashCommand.with("embed", "Send message in a embed",
>                         List.of(
>                                 SlashCommandOption.create(SlashCommandOptionType.STRING, "message", "Message (seperate title from description with |, for new line use \\n)", true)))
>                 .setDefaultEnabledForPermissions(PermissionType.MANAGE_MESSAGES)
>                 .createGlobal(api)
>                 .join();
>         SlashCommand.with("pool", "Create a yes/no pool",
>                         List.of(
>                                 SlashCommandOption.create(SlashCommandOptionType.STRING, "message", "Message (seperate title from description with |, for new line use \\n)", true)))
>                 .setDefaultEnabledForPermissions(PermissionType.MANAGE_MESSAGES)
>                 .createGlobal(api)
>                 .join();
>         logger.info("Complete");
>     }
> }
> ```

I think my recommendation would be to add the slashcommands in 1 go instead of adding 1 each time and joining. This could be a network issue and the .join() makes every creation blocking.

**Comment by cmclient** [comment]
> I also could not reproduce the behavior you described, using Javacord 3.8.0 and Java 11.
> 
> Side note: Registration of the Commands did take 15+ seconds when I tried it - using [`DiscordApi#bulkOverwriteGlobalApplicationCommands`](https://javadoc.io/doc/org.javacord/javacord-api/latest/org/javacord/api/DiscordApi.html) instead took less than half a second.

Works better with bulkOverwriteGlobalApplicationCommands. Bot loading is quicker and RAM usage dropped to 600 MB from 2 GB. But its still slower and ram usage is higher than almost same bot in JDA - on JDA its 74 MB RAM usage.

**Comment by felldo** [comment]
How many servers is your bot in and how many members do these servers have?

**Comment by cmclient** [comment]
> How many servers is your bot in and how many members do these servers have?

1 server 150k people
this shouldn't be a issue beacuse it's happen only on bot loading

**Comment by felldo** [comment]
> 1 server 150k people
> this shouldn't be a issue beacuse it's happen only on bot loading

If you also log in the same way as your minimal reproducible example, the RAM usage might be normal. Javacord by default caches all members, and since you also have the presence intent when logging in with all intents, even more data is being cached. Depending on how you log in with JDA (create, createLight, createDefault), there are differences on what is being cached by default.
But using `bulkOverwriteGlobalApplicationCommands` doesn't make a difference in RAM usage, since it effectively creates the same objects using the same class. The only difference should be the noticeable less amount of time it takes to execute the code since you don't wait for each command separately to be created.

So this will leave us with the high CPU usage, which I still can't believe has anything to do with Javacord in the way you showed us how you use it. Many other users are already on version `3.8.0` and haven't noticed anything, especially since the code for slash commands shouldn't have had any significant changes for quite some time. So I'm pretty confident to say that there is something wrong in your code or PC, that causes high CPU usage, since for @Saladoc and me it works fine with the MRE you provided to us.
