### ISSUE TITLE
Adding image to embed in immediate interaction responder does not work

### ISSUE THREAD

**Issue by masecla22** [Javacord/Javacord#1314]
### Javacord version

3.8.0

### Steps to reproduce

1. Create a command with subcommands (unsure if a simple command will work)
2. Have an interaction on the command
3. Reply to the interaction with an immediate responder containing an embed with just an image.

```
                interaction.createImmediateResponder().addEmbed(
                                new EmbedBuilder()
                                        .setImage(tempFile))
                        .respond();
```

4. Fix it, by introducing an edit step which forces the image to work
```
                interaction.createImmediateResponder()
                        .addEmbed(new EmbedBuilder().setTitle("loading..."))
                        .respond()
                        .join()
                        .removeAllEmbeds()
                        .addEmbed(
                                new EmbedBuilder().setImage(tempFile)
                        ).update();
```

### What is expected?

I would expect the image to show up no matter what.

### What is actually happening?

![image](https://github.com/user-attachments/assets/483d2829-48d1-4211-8249-1cd1213a1540)

You can see the image does not show up unless we force the edit. (You can see the two scenarios)

**Comment by Mysterypotatoguy** [comment]
[Immediate responses cannot attach images](https://javacord.org/wiki/basic-tutorials/interactions/responding.html#responding-immediately-after-receiving-an-interaction), but you are able to either edit in the image as you are doing, or use `respondLater`

**Comment by masecla22** [comment]
Ah, I see, thank you very much!
