### ISSUE TITLE
EventDispatcher is not working properly.

### ISSUE THREAD

**Issue by Bastian** [Javacord/Javacord#251]
My bot stopped receiving events in one of its servers. It's most likely a bug in the EventDispatcher class.

**Comment by BtoBastian** [comment]
![](https://i.imgur.com/DWY9yAQ.png)

After removing the entry in `runningListeners` the bot started answering all missed events.
So the issues is related to the listener not being removed from `runningListeners`.

**Comment by BtoBastian** [comment]
https://github.com/BtoBastian/Javacord/commit/e078151af2edb8656364d13ff37acdd04dd42b07 might fix this issue. However, my log didn't show the 2 minute error message (`Interrupted a xyz listener thread, because it was running over 120 seconds!`), so it might be caused by something else.

**Comment by Bastian** [comment]
As there weren't any new bug report and the EventDispatcher was heavily reworked in #322, I'll assume that this is fixed now.
