### ISSUE TITLE
Exceptions for uncached users

### ISSUE THREAD

**Issue by Bastian** [Javacord/Javacord#261]
Even though events only get dispatched for servers where all members are cached, some handlers might try to access uncached users which can cause `NullPointerException`s or `AssertionError`s.

**Comment by BtoBastian** [comment]
#261 should fix this in most cases.
However, there can still be some race condition which can cause `AssertionError`, if methods like `getUser()` get called for users who are no longer in the cache (but were before).

**Comment by Bastian** [comment]
Closing this in favor of #450 which covers this issue.
