### ISSUE TITLE
Embed not working in 2.0.17

### ISSUE THREAD

**Issue by OpperDev** [Javacord/Javacord#281]
I'm using version 2.0.17,
When I create an Embed (with EmbedBuilder)
And that I send it in a channel,
Nothing is sent!
Here is my code:

> `EmbedBuilder embed = new EmbedBuilder().setTitle("Avaiable commands:").setDescription("(Only for staff)").setColor(Color.GREEN)
                .addField("Punishment commands: bans", "-ban (discordID) (reason) | -tempban (discordID) (reason) (time) (unit)", false)
                .addField("Punishment commands: mutes", "-mute (discordID) (reason) | -tempmute (discordID) (reason) (time) (unit)", true)
                .addField("Videos announces", "-channel (remove/add) (youtube-channel-url)", true)
                .addField("Tweets announces", "-twitter (remove/add) (twitter-account-url)", true)
                .setFooter("Bot by OpperDev");
        message.getChannelReceiver().sendMessage(msg, embed);`

**Comment by Vampire** [comment]
Did you consider switching to v3? It is highly recommend to do so and if there was a bug, it is very likely it is not there anymore, as v3 is a complete rewrite that is almost finished.

**Comment by BtoBastian** [comment]
Hey,

it's highly recommended to switch to v3 which will be release very soon and has more features and less bugs than v2. About the actual issue: Did you try adding a `get()` after `sendMessage(...)`? 
```java
try {
    message.getChannelReceiver().sendMessage(msg, embed).get();
} catch (ExecutionException e) {
    e.printStackTrace();
}
```
should throw an exception with more information. See [`Future#get()`](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/Future.html#get()).
