### ISSUE TITLE
javadoc link redirects to 127.0.0.1

### ISSUE THREAD

**Issue by DeStilleGast** [Javacord/Javacord#317]
under Useful Links in the wiki there is a link for javadocs, but it redirects to 127.0.0.1, but I don't have a webserver running localy:

the link that it reference: https://ci.javacord.org/javadoc/

**Comment by Bastian** [comment]
We are rewritting the README at the moment for the release of v3 (see https://github.com/Javacord/Javacord/pull/312).

For now you can view the JavaDocs under the following URL: https://jitpack.io/com/github/Javacord/javacord/javacord-api/v_3-SNAPSHOT/javadoc/

**Comment by Bastian** [comment]
Fixed.
We now have https://docs.javacord.org/
