### ISSUE TITLE
Methods to set a proxy for REST-calls / the websocket

### ISSUE THREAD

**Issue by Bastian** [Javacord/Javacord#360]
At the moment it is not possible to set a proxy for the REST-calls and the websocket.

**Comment by Vampire** [comment]
Actually for the REST calls there is.
OkHttp uses the system default proxy selector if no proxy and no proxy selector is set explicitly, so the standard Java properties for setting a proxy should at least work fine with the REST part for which we use OkHttp.

**Comment by Vampire** [comment]
Besides the standard system properties, the system default proxy selector should also be taken into account.
So as the system default proxy selector handles the standard system properties basically it should probably be:
- If proxy is set explicitly via `DiscordApiBuilder#setProxy`, use it
- If not, but proxy selector is set via `DiscordApiBuilder#setProxySelector`, use it
- If not, use the system default proxy selector from `ProxySelector.getDefault()`
This should probably be all that is necessary to have it correctly, besides some docs.

**Comment by Vampire** [comment]
I'm working on this, you can assign me here
