### ISSUE TITLE
The 50/1 global REST ratelimit is not handled properly

### ISSUE THREAD

**Issue by Bastian** [Javacord/Javacord#361]
At the moment, hitting the global 50/1 ratelimit (e.g. by trying to send 100 DMs to 100 different users at the same time) is not handled properly by Javacord.

**Comment by Bastian** [comment]
This is actually pretty hard to prevent in a multithreaded environment.
As these actions are usually in different buckets, we cannot prevent hitting 429s, as the request already got sent, before we received the information that we got ratelimited globally.

So the only thing we can do, is to immediately stop sending new requests once we hit a global ratelimit, but it's no possible to preemptively prevent hitting it without hardcoding the global ratelimit.

**Comment by MinnDevelopment** [comment]
When using the same builder to start shards you could add a service which only manages the global rate-limit and use its state for all rate-limit handlers. For instance:

1) start queue
2) check global rate-limit (from service)
3) if rate limit, delay queue
4) execute
5) if hit global rate-limit set on service, delay queue
6) deque
7) if not done, goto 2

**Comment by Bastian** [comment]
Thank you for the suggestion.

The problem I have is not about multiple shards, but within a single shard.
One of Javacord's users had a bot which had to send DMs to >1000 members of a server (no spam, it was a valid use case) and this caused issues, as each of these actions has its own bucket and thus all requests were sent from different threads. As a result, the first 429 was received after the bot already sent tons messages.

Of course the user can break it up into smaller batches himself, but Discord wants us to preemptively prevent something like this. I just don't think it's possible in this use-case without executing **every** action sequentially **or** hard-code this limit. Different shards make this even more complicated ofc, but as long as the shards are on the same machine(/runtime), this isn't a real problem.
