### ISSUE TITLE
Audio support

### ISSUE THREAD

**Issue by Bastian** [Javacord/Javacord#390]
## Api design
This is a description about Javacord's upcoming audio api. It is "work in progress" and might change significantly during development. Feedback is very appreciated.

### Joining a voice channel
Joining a voice channel is nothing special. You call `#connect()` on a `VoiceChannel` and receive an `CompletableFuture<AudioConnection>`. If the bot is already connected to another voice channel on the same server, it will leave the old channel and join the new one (aka. move).
```java
VoiceChannel channel = ...;
channel.connect().thenAcceptAsync(connection -> {
    // Do stuff
});
```

### AudioSources
To be flexible with all various types of inputs, there will be an interface `AudioSource` with different implementations. Creating an audio source for a YouTube video might look like this:
```java
AudioSource source = new YoutubeAudioSourceBuilder()
    .setUrl("https://youtu.be/NvS351QKFV4")
    .build();

// Maybe, there might be a "shortcut" to skip the builder for "simpler" sources
AudioSource source = YouTubeAudiSource.of("https://youtu.be/NvS351QKFV4");
```
An audio source from an mp3 file, might look like this:
```java
AudioSource source = new FileAudioSourceBuilder()
    .setFile(new File("C:/Users/Bastian/Music/moskau.mp3"))
    .build();
```

Javacord will not provide any implementation for `AudioSource`s, but just interfaces like
- `AudioSource` 
- `PauseableAudioSource` -> Has additional methods like `#pause()` and `#unpause()`
- `SeekableAudioSource`/`NavigableAudioSource` -> Has additional methods like `#jumpToPosition(int, TimeUnit)`
- `...` -> ...

The actual implementation will be moved into an own repository or module.

### Sending audio
Sending audio is also very simple. Audio connections will have a queue and just consume the audio sources one after the other. You can also queue an audio source multiple times.
```java
AudioConnection connection = ...;
AudioSource source = ...;
connection.queue(source);
```

### Handling exceptions
Exceptions will be treated like normal "events". 
```java
AudioConnection connection = ...;
connection.addAudioSourceExceptionListener(event -> {
    event.getException().printStackTrace();
    // Skip the audio source
    event.getConnection().dequeue(event.getAudioSource());
});
```
Like every other Javacord listener, it can also be attached to other objects. In this case you can attach the listener to `DiscordApi`, `Server`, `VoiceChannel`, `AudioConnection`, `AudioSource`.

### Interacting with the queue
Sometimes you might want to interact with the current queue. If you want to pause the currently played song, it may look like this:
```java
AudioConnection connection = ...;
connection.getCurrentSource()
    .flatMap(source::asPauseableAudioSource)
    .ifPresent(PauseableAudioSource::pause);
```

You can also use other events. The following example will loop the last song of the queue until a new source get's queued.
```java
connection.addAudioSourceFinishedListener(event -> {
    if (!event.getNextSource().isPresent()) {
        event.getAudioConnection().queue(event.getSource().copy());
    }
});
```

### Muting vs Pausing
- Muting -> There will be no sound. After unmuting, the audio source will be at a different "position"
- Pausing -> The will be no sound. After unpausing, the audio source will continue at the previous "position"

Every audio source can be muted, but not every audio source can be paused (e.g. a Twitch livestream or microphone input). 

### Real muting vs displaying a "mute" in the UI
To show the mute icon, you can call `AudioConnection#setSelfMuted(boolean)`. This is only optical and does not affect the audio source and audio connection.
![](https://i.imgur.com/FQ3v69a.png)

Real muting can be achieved with `AudioSource#setMuted(boolean)`.

### Streaming vs Downloading
Sometimes you want to pre-download a whole audio source and sometimes you want to download it while it's played. E.g. it's fine to pre-download a 2 minute song from YouTube, but downloading [Keyboard Cat! 50 HOURS](https://www.youtube.com/watch?v=kIvobmqIJu8) might not be the best idea. Whether an audio source will be streamed or downloaded depends on the audio source. Some are only streamable (e.g. a Twitch livestream or microphone input) while others can be downloaded.
```java
AudioConnection connection = ...;
DownloadableAudioSource source = new YoutubeAudioSourceBuilder()
    .setUrl("https://youtu.be/NvS351QKFV4")
    .build();

// Download the song before playing it
source.download().thenAccept(connection::queue);
```

### Buffering audio source
Whether an audio source will be buffered or not is up to the implementation. Where it makes sense, it can be set in the builder:
```java
// The audio-source will buffer 30 seconds of the YouTube video
AudioSource source = new YoutubeAudioSourceBuilder()
    .setUrl("https://youtu.be/kIvobmqIJu8")
    .setBufferSize(30, TimeUnit.SECONDS)
    .build();
```

### Reusing an audio source
Audio sources can be reused by calling the `copy()` method. This creates a copy of the audio source which plays exactly the same audio but will start from the beginning.

```java
AudioConnection connection1 = ...;
AudioConnection connection2 = ...;
AudioSource source = new YoutubeAudioSourceBuilder()
    .setUrl("https://youtu.be/kIvobmqIJu8")
    .build();

connection1.queue(source);
connection2.queue(source.copy());

// Optional: When downloading the audio source first, `copy()` will use the downloaded audio as well and does not re-download it
seource.download().thenAccept(source -> {
    connection1.queue(source);
    connection2.queue(source.copy());
})
```

### Keep used audio source data in memory
You can keep already played audio source data in memory to not require copies of the audio source to not require them to redownload them.
```java
// The YouTube video can be re-used after being played once without having to re-download it.
AudioSource source = new YoutubeAudioSourceBuilder()
    .setUrl("https://youtu.be/kIvobmqIJu8")
    .setKeepInMemoryAfterUsage(true)
    .build();
```

### Synthesizer
Synthesizers can be applied to any audio connection. A synthesizer is just a functional interface with a method that accepts an opus packet as parameter and returns a (modified) opus packet.
```java
AudiConnection connection = ...;
int volume = 150; // 150%
connection.addSynthesizer(new SoundAmplifier(volume));
```
This allows "simple" functions like adjusting volume, but also allows for more complex functionality like voice changers or other modifications.

## Implementation
Development of the api and it's implementation didn't start so far. However there's a [Javacord fork](https://github.com/Mysterypotatoguy/Javacord) by [Mysterypotatoguy](https://github.com/Mysterypotatoguy) with working audio support. We might use it as base for Javacord's audio support. 

## Roadmap
Audio support has a very high priority for Javacord, but there's no ETA.

**Comment by 0xCarti** [comment]
Add support for receiving audio as a combined source.
