### ISSUE TITLE
Allow users to disable specific event handlers

### ISSUE THREAD

**Issue by Bastian** [Javacord/Javacord#402]
It should be possible to disable high-frequent event handlers (e.g. for presence updates) when they are not needed. 

Unsolved problems/questions:
* Some handlers are mandatory for Javacord to work properly. Should it be possible to disable them? 
* If it's possible, how do we tell the user which are safe to disable and what impact they have? In a Wiki article? In the JavaDocs? With a method (`isSafeToDisable`)?

**Comment by Saladoc** [comment]
Alternatively: Do not expose them. Better check which ones are essential and activate the other ones only if a listener is registered that depends on information from that handler. Deactivate if all dependent listeners are unregistered.

**Comment by Bastian** [comment]
Most (it not all) handlers are also used to update the cache. E.g. `user.getStaus()` would require to listen for presence updates.

**Comment by Bastian** [comment]
Maybe we should not allow to disable specific event handlers, but specific features, especially performance heavy ones:
```java
api.disableFeatures(USER_STATUS_UPDATES, USER_GAME_UPDATES, MESSAGE_PINS);
```

Some features can be disabled without any issues (e.g. the ones in the example above). It get's more complicated for some other features though.

**Comment by Bastian** [comment]
Superseded by gateway intents: https://github.com/Javacord/Javacord/issues/522
