### ISSUE TITLE
Rework role position getters

### ISSUE THREAD

**Issue by Bastian** [Javacord/Javacord#417]
At the moment `Role#getPosition()` just returns the `position` field from Discord. As we all know, Discord is weird and thus roles in the same server can have the same position in which case the id is used to test which role is higher. 

As this is unintuitive behavior, we should rename the current method to `getRawPosition()` and add a new `getPosition()` method that returns the "real" unique position of the role. This will also be consistent with what we are already doing for channels.

**Comment by burdoto** [comment]
Name/Doc proposal: `#getRawPosition` as alreay used and `#getAbsolutePosition` which returns the "true" position of a role; or rather a JavaDoc line that describes that `#getPosition` returns the "user-absolute" position
