### ISSUE TITLE
Send messages directly to webhooks

### ISSUE THREAD

**Issue by Bastian** [Javacord/Javacord#422]
It should be possible to send messages to webhooks with Javacord.

- The `Webhook` class should extend `Messageable`
- The `MessageBuilder#send()` method should support webhook urls (maybe `sendToWebhook()` to make it more clear?) and of course `Webhook` also objects
- `MessageBuilder#setEmbed(...)` should be replaced with `#addEmbed(...)` (deprecate, not remove `#setEmbed()`!)
- Webhooks should be properly ratelimited with automatic retries -> I don't know if the ratelimit headers are the same. Hopefully we can just use our normal `RestRequest` class without any adjustments.

**Comment by Bastian** [comment]
Webhooks also allow to set custom display names and avatar when sending the message.
So we'll also need `MessageBuilder#setWebhookDisplayName(...)` and `#setWebhookAvatar(...)`.
I would like to have the webhook in the name, because otherwise it might be confusing if you don't know that `MessageBuilder` can also be used for webhooks.

**Comment by Saladoc** [comment]
Maybe it would be better to have a separate `WebhookMessageBuilder` with those functions, have it extend `MessageBuilder` and have a `MessageBuilder#forWebsocket` function that basically calls a copy constructor on the subclass. 
That way people need to explicitly create a `WebhookMessageBuilder` or convert a `MessageBuilder` and every risk of confusion is gone.

**Comment by Bastian** [comment]
With the introduction of slash commands, this feature became significantly more important.
