### ISSUE TITLE
Make all entities immutable

### ISSUE THREAD

**Issue by Bastian** [Javacord/Javacord#454]
A lot of out current design problems are caused by mutable objects and collections. Some of these problems include but are not limited to:
* Poor performance of methods like `DiscordApi#getCachedUsers()`, caused by defensive copies of collections. Immutable collections can decrease the time complexity of these methods from `O(n)` to `O(1)`
* Changing channel types (`ServerNewsChannel`<=> `ServerTextChannel`)
* Users being confused on when to keep a reference to an object and when not

As a long term goal (maybe even a new major version?), I would like to switch completely to immutable objects and collections. 
There are a few options for immutable collections available:
* [Vavr](http://www.vavr.io/vavr-docs/) being my current favorite for immutable collections. It comes with a lot of other features as well, which I'm not sure if they really provide any benefit. However, as the artifact size is pretty small, we can still use this project only for immutable collections, without using the other features. They have their own collection classes, but provide a `asJava()` method to wrap their classes. This means our api can remain the same.
* [PCollections](https://github.com/hrldcpr/pcollections) gets recommended a lot on StackOverflow and similar forums seems to no longer be active.
* [pcj](https://github.com/pmem/pcj) is a pretty small project
* [Dexx Collections](https://github.com/andrewoma/dexx) is a port of Scala's immutable collections
* [totallylazy](https://github.com/bodar/totallylazy/) is no longer active
* [JImmutable Collections](https://github.com/brianburton/java-immutable-collections) looks very good, but is not very popular (20 stars) and not very active (last commit 1 year ago)

Immutable objects will not need any additional libraries.

**Comment by Bastian** [comment]
Immutable objects will also allow us, to easily add more general events, e.g.:
![Events](https://user-images.githubusercontent.com/5033001/54868257-f1427200-4d8a-11e9-9820-e6142d4b53bd.png)
I'm not sure how useful this would be, but it would certainly be easily doable with immutable objects.

**Comment by Bastian** [comment]
I've increased the priority of this PR, because our current solution can even cause internal `ConcurrentModificationException`s, e.g. when creating defensive copies.
If we did not switch to immutable collections, we would need a lot of additional synchronisation.

**Comment by Bastian** [comment]
Okay, maybe not "Go full immutable" but at least all entities should be immutable.

**Comment by Bastian** [comment]
After letting this issue rest for a while, I'm currently thinking about a different approach:

* Have an immutable cache that stores primitive POJOs
* These POJOs contain the raw data that makes up a Discord entity and **do not** contain any references to other entities (only IDs). E.g., a `ServerData` object would only contain a list of channel ids, not a reference to the channels.
* The POJOs are immutable and ideally generated with a library that takes care of all the boilerplate that comes with immutable objects in Java (think about [Kotlins `copy()` method](https://kotlinlang.org/docs/data-classes.html#copying) in data classes vs dozens of setters in Java)
* The user-facing entities of the public API are wrappers for these POJOs and only hold a reference to the immutable cache and the id for their object
* Entities are not stored anywhere but dynamically created whenever they are needed
* The cache is responsible for maintaining efficient indices (like it already does)

The entities could look like this (simplified):
```java
public class ServerTextChannelImpl implements ServerTextChannel  {

    private final EntityCache cache;
    private final long id;
    // Not really necessary, but convenient because you don't have to query it every time
    private final ServerTextChannelData selfData;
    
    public ServerTextChannelImpl(EntityCache cache, long id) {
        this.cache = cache;
        this.id = id;
        selfData = cache.get(ServerTextChannelData.class, "id", id); // Could look different
    }
    
    @Override
    public String getName() {
        return selfData.getName();
    }

    @Override
    public Server getServer() {
        return new ServerImpl(cache, selfData.getServerId());
    }
    
    // ... Other methods, e.g, to send messages

}
```

Pros:
* Simplified caching
* Cache as "single point of truth"
* The cache could be its own module
* Clear structure
* ... to be continued

Cons
* Lists would be `O(n)` again
* More boilerplate/overhead (maybe?)

**Comment by Rubydesic** [comment]
You listed a lot of immutable collections libraries but not the arguably most popular, Guava. Is there a specific reason for excluding it?

**Comment by Bastian** [comment]
> I missed that all your libraries have immutable collections that can be modified without copying the entire thing. Whoops

Indeed. From what I've heard, the immutable data structure from Guava are great for data that is truly immutable and never changes. They remove a lot of overhead that comes with the usual mutable data structures and thus are a bit faster and more memory efficient.

**Comment by Bastian** [comment]
Going full immutable was not well received and I will no longer pursue this concept.
A new idea for a mutable cache module can be found in https://github.com/Javacord/Javacord/issues/805
