### ISSUE TITLE
message.getContent() & message.getReadableContent() returns emojis as "?"

### ISSUE THREAD

**Issue by KleinDevDE** [Javacord/Javacord#465]
Message
```
[23:50] KleinDev: :a:
```

Code
```java
if (TempData.debug) {
            LogManager.log(LogType.DEBUG, "EonaChatListener getContent() | " + message.getContent(), true);
            LogManager.log(LogType.DEBUG, "EonaChatListener getReadableContent() | " + message.getReadableContent(), true);
        }
```

Output
```
[23:50:10.710] DEBUG   | event.getMessageContent() -> ?
[23:50:10.716] DEBUG   | EonaChatListener getContent() | ?
[23:50:10.717] DEBUG   | EonaChatListener getReadableContent() | ?
```

Class: `org.javacord.api.entity.message.Message`
Who gave me the object: `org.javacord.api.event.message.MessageCreateEvent`

**Comment by Bastian** [comment]
Discord converts `:a:` and other non-custom emoji tags into Unicode emojis. Your console is most likely not able to display these Unicode emojis properly and thus display me them as `?`.
See https://en.wikipedia.org/wiki/Specials_(Unicode_block)#Replacement_character

**Comment by Bastian** [comment]
Could you solve the issue? :)

**Comment by Bastian** [comment]
I'm closing this, as it is not a Javacord issue.
Feel free to join [our Discord server](https://discordapp.com/invite/0qJ2jjyneLEgG7y3) if you need help with anything :slightly_smiling_face:
