### ISSUE TITLE
Replace AudioConnection#queue(...) with AudioConnection#set(...)

### ISSUE THREAD

**Issue by Bastian** [Javacord/Javacord#469]
Instead of having a primitive built-in queue, it might better to keep it simple and only allow users to set a single audio source. We can still provide a utility class that supports the user with the queue logic.

**Comment by Saladoc** [comment]
Should a `AudioSourceFinishedEvent` be dispatched if an Audio Source is not finished but "ejected"?

**Comment by Bastian** [comment]
Good question. 
Maybe we should change the name and just add a `getReason()` method or something similar.
I'm just unsure about the listener/event name then.
`AudioSourceStoppedEvent`? -> No
`AudioSourceEjectEvent`? -> Not sure about this one. I don't really like it :/

**Comment by Vampire** [comment]
eject? We are not handling tapes. :-D
What is the meaning?

**Comment by Vampire** [comment]
abort?
dequeue?

**Comment by Saladoc** [comment]
I was referring to the audio source being dropped for whatever reason (disconnect, method call, replaced with another audio source) before being finished.
