### ISSUE TITLE
java.lang.NoSuchMethodError: org.apache.logging.log4j.Logger.debug(Ljava/lang/String;Ljava/lang/Object;Ljava/lang/Object;)V

### ISSUE THREAD

**Issue by Gary50613** [Javacord/Javacord#506]
hello I am developing a spigot plugin with Javacord now
but it show a error says
`java.lang.NoSuchMethodError: org.apache.logging.log4j.Logger.debug(Ljava/lang/String;Ljava/lang/Object;Ljava/lang/Object;)V`
I have already put Javacord and **org.apache.logging.log4j** into classpath

**Comment by nekokatt** [comment]
Have you checked that the correct version of log4j is present? If you are using maven or gradle, it should be putting this into the classpath for you; you should not have to be doing anything yourself other than specifying the dependency, I would hope.

Can you provide the full stacktrace if possible so the other guys who have more experience with this API can see what code is making this call?

**Comment by Vampire** [comment]
I guess this is the usual problem people have with older versions of Bukkit, where a very old version of log4j is included and preferred over the one you ship with your plugin.
Afair the only working solutions were to either use a newer Bukkit version or to relocate log4j in your shaded fat jar.

**Comment by Gary50613** [comment]
thanks for the help :D

**Comment by Electroid** [comment]
We also ran into this, it would be great to add this to an FAQ on how to resolve the issue without upgrading Bukkit.
