### ISSUE TITLE
Gradle Importing fails for no apparent reason (lol)

### ISSUE THREAD

**Issue by burdoto** [Javacord/Javacord#516]
Since Version 3.0.5, Gradle fails to resolve both the JitPack and the `jcenter()` release:
![grafik](https://user-images.githubusercontent.com/42473485/70148568-baa55100-16a6-11ea-9681-a2d09f35e1b3.png)
![grafik](https://user-images.githubusercontent.com/42473485/70148608-c729a980-16a6-11ea-99fd-c9df9e8bbe25.png)

**Comment by Bastian** [comment]
Did you try to clear your Gradle cache?
