### ISSUE TITLE
Incorrect return type of RichInvite.getInviter()

### ISSUE THREAD

**Issue by Pepich** [Javacord/Javacord#519]
Occurs in Javacord Version 3.0.5

[RichInvite.getInviter()](https://github.com/Javacord/Javacord/blob/master/javacord-api/src/main/java/org/javacord/api/entity/server/invite/RichInvite.java#L17) has return type User, however the docs mark it as Optional<User> resulting in getInviter potentially returning null.

Type according to [docs](https://discordapp.com/developers/docs/resources/invite):
inviter? | user object | the user who created the invite

**Comment by Bastian** [comment]
It should also be moved to the "normal" `Invite` object, as it is no longer part of the invite metadata.
