### ISSUE TITLE
No ReactionEvents for uncached private channels

### ISSUE THREAD

**Issue by VolcanoCookies** [Javacord/Javacord#524]
Version: 3.0.5
Version Commit ID: 917e4b351e5c8a1f53cb02be68d05f06b5477986

It appears that globally attached ReactionAddListener and ReactionRemoveListener do not receive reaction events from *uncached?* private channels.

The following code does not receive ReactionEvents from private channels, unless a private message is first sent to the bot after it has started, or the private channel is opened in any other way. *Message loads the channel into cache?*

```
api.addReactionAddListener(event -> {
    System.out.println("Event received");
});
````

**Comment by coaxial1** [comment]
This is probably related to https://github.com/discord/discord-api-docs/issues/1316

**Comment by Bastian** [comment]
@VolcanoCookies thank you for the bug report and @coaxial1 thanks for the hint.

I see two options:
1. We fix this bug now by making the channel in all message related events optional (including message edit and message delete) and only provide the channel id and utility methods to interact with the channel without having to fetch the channel object.
2. Wait for the v7 gateway version:
[![image](https://user-images.githubusercontent.com/5033001/79043119-80703100-7bfd-11ea-9265-aab8fea63ea2.png)](https://github.com/discord/discord-api-docs/issues/184#issuecomment-312960055)
Unfortunately jhgg wasn't clear if in v7 the full channel information will also be available for reactions, edits and deletions or only for message create events.
