### ISSUE TITLE
http status codes being ignored

### ISSUE THREAD

**Issue by Pepich** [Javacord/Javacord#526]
JavaCord will attempt to parse Discord's repsonse on certain actions (e.g. sendMessage()) without checking the http response code. This results in HTML being parsed as JSON, and an exception being thrown. Attached is a stacktrace of when the API returned an HTTP 502, but JavaCord tried parsing the response as JSON anyway.

https://hastebin.com/zodofazefi.php

**Comment by Bastian** [comment]
Thank you for reporting! 👍 
Do you still have the error log? From my experience, hastebin has been pretty unreliable in the past 2 years. At the moment it just displays a blank page for me :(

**Comment by Pepich** [comment]
Let‘s try a slightly more reliable service the. https://gist.github.com/Pepich/a7bbb9cc5f8cc8bc634aa0df64b75437#file-exception-log
The exception was thrown upon joining a message send. If you need more info lemme know :)

**Comment by Vampire** [comment]
As far as I remember when we last talked about this on Discord, the outcome was, that the HTTP status is checked, but only after the content is parsed as JSON already.

**Comment by Pepich** [comment]
[Here's another similar instance](https://gist.github.com/Pepich/cf388c5474e8fc898614aaf36b5cb546) - this time it has nothing to do with an error message but instead was caused by the connection being dropped shortly before/after it. The message that Discord returned is unknown to me as the stacktrace didn't reveal any info about it :/
