### ISSUE TITLE
Remove support for non-bot users (selfbots/client accounts)

### ISSUE THREAD

**Issue by Bastian** [Javacord/Javacord#540]

**Comment by Swag1400** [comment]
nah keep supporting it g

**Comment by Joshix-1** [comment]
It is full of bugs and not worth supporting. 
So if you want to use that 'feature' you just could keep using an older version.

**Comment by ChA0S-f4me** [comment]
> nah

O, vi is anglii?

**Comment by CodecNomad** [comment]
Sad
