### ISSUE TITLE
Support lazy loading users

### ISSUE THREAD

**Issue by Bastian** [Javacord/Javacord#541]
Because of the upcoming change regarding intents (see https://github.com/Javacord/Javacord/issues/522 for reference), we have to add support for lazy loading users.

**Comment by Bastian** [comment]
## Requesting all server members on startup

Currently, we request all server members on startup (using the [REQUEST_GUILD_MEMBERS](https://discord.com/developers/docs/topics/gateway#request-guild-members) gateway message). There are some limitations to this endpoint if we use intents:
![image](https://user-images.githubusercontent.com/5033001/81070663-d88c1180-8ee3-11ea-8a7b-67e412f3a8fe.png)
This basically means:
* With the `GUILD_MEMBERS` intent, we can get a list with all users in a server including roles, usernames, avatar, isBot, etc. (we get a [guild member object](https://discord.com/developers/docs/resources/guild#guild-member-object) which also contains a [user object](https://discord.com/developers/docs/resources/user#user-object)
* With the `GUILD_PRESENCES` intent, we can get additional presence information about the user (a [presence object](https://discord.com/developers/docs/topics/gateway#presence)), mainly the users's status (online/offline, which game, etc.)

**Comment by Bastian** [comment]
Ok, here's my current idea/plan.

## Regarding user presences (`GUILD_PRESENCES` intent not set)

This is a minor one: Presence information is nice to have, but not really important. Theoretcially, we could just leave everything like it is. Alternatively, we could extract all presences into an own object and make this object optional. This can be decided later as nothings breaks currently.

## Regarding guild members (`GUILD_MEMBERS` intent not set)

This is the scary one!
Without this intent we
* Cannot see what user is part of a server
* Cannot receive any updates that can help us to update the cache

But we can
* Get this information on events (all user-related events include both a [user object](https://discord.com/developers/docs/resources/user#user-object) and a [member object](https://discord.com/developers/docs/resources/guild#guild-member-object)

What does this mean for us?
* When the `GUILD_MEMBERS` intent is not set, we do not keep any users in the cache
* For every user-related event we just create a new user object

We also have to re-think our current member implementation: Instead of storing all the member information (roles, etc.) we should move this information in the `User` object. Maybe this is even the time to finally introduce a Member interface 🤯?

**Comment by Bastian** [comment]
Maybe this is also a good moment to introduce https://github.com/Javacord/Javacord/issues/468 + make the `User` class immutable in general.

**Comment by Bastian** [comment]
### Roadmap
1. Implement the `EntityCache` from https://github.com/Javacord/Javacord/issues/468
2. Add a `Member` object
3. Lazy loading support

**Comment by coaxial1** [comment]
> Presence information is nice to have, but not really important.

Just wanted to mention that **GUILD_PRESENCES** is the only way to know about username changes (not nicknames). You mentioned that [here](https://discordapp.com/channels/151037561152733184/151326093482262528/587612624695590913). Discord mentioned that they are possibly changing that [here](https://github.com/discord/discord-api-docs/pull/1307) (see Open Questions and Discussion), but until we get that info through another event, I'd consider presences as pretty important as library users would probably expect cached usernames to be accurate at all times, for example, if they have **GUILD_MEMBERS** enabled and **GUILD_PRESENCES** disabled

**Comment by Bastian** [comment]
I remember Discord saying that it is actually very rare for user information to change and that they think that it is enough to update it once the bot receives an event with that user (e.g., message create).

It's not like we can change anything, besides adding a comment in the JavaDoc that updates for usernames might be delays if the `GUILD_PRESENCES` intent is not set.

**Comment by Bastian** [comment]
# 👫 New user caching behavior

We differentiate between two states: Enabled user-cache and disabled user-cache

## Disabled user-cache 🛁

The user cache can either be disabled manually but is also disabled when the `GUILD_MEMBERS` is not set.
If caching is disabled, we simply create a new immutable member and user object everytime we need it (e.g., for an event).

## Enabled user-cache 🛀

We will have two caches:
* A member cache
* A user cache

We only cache users that have a common server, every other user is created on the fly and not put into the cache. As soon as a user in the cache has no shared server anymore (e.g., our bot left the server or the user itself left the server) they will be removed from the cache.

User and member objects are always immutable.

**Comment by coaxial1** [comment]
Would it be possible to also have users in the cache that don't have a common server but an open DM channel? This is important for DM operations on shard 0 if the user sending a DM is only members of servers on other shards.
