### ISSUE TITLE
Follow the All Contributors specification 

### ISSUE THREAD

**Issue by Bastian** [Javacord/Javacord#559]
https://github.com/all-contributors/all-contributors

Maybe in conjunction with https://github.com/Javacord/Javacord/pull/553

**Comment by Saladoc** [comment]
I definitly wouldn't put it directly in the readme though, but another page would be alright.

**Comment by Bastian** [comment]
Why not?
That's the recommended place, unless a project has way too many contributors.

**Comment by Saladoc** [comment]
Personal preference. I don't consider something like that necessary information, so I'd not put it in a README. In my opinion a README should contain only the basic information about a project, namely its scope, a basic "how to get started" and anything beyond that should be on a different page.

Recognizing contributors is a good move, but putting it on the readme (the "landing page" so to speak) feels like shifting the focus away from the "What is this" to the "Who made this", which feels significantly less relevant for the decision to use the library.

**Comment by Vampire** [comment]
I see it like @Saladoc.
Contributions are important and all sorts, including reporting bugs, suggesting features, spreading word, ....
But imho nothing that should clutter the readme.
Also the all contributors page says
> Use the project README (**or another prominent public documentation page in the project**) to recognize the contributions of members of the project community.

**Comment by KILLEliteMaste** [comment]
Do you think it shouldn't be mentioned at all in the readme or just the list of contributors? Was thinking about leaving it like it's in the PR #1036 (a small note that we follow the all-contributors) and then redirecting to a `CONTRIBUTORS.md` where the contributors will be added

**Comment by Saladoc** [comment]
I would probably include a paragraph on contributing in the readme (roughly wherethe Version Numbers or Support paragraphs are) with a little text that 1) encourages contributing, redirects to issues etc, maybe even the good-first-issue issues (if we use that tag) and in that text, links to `CONTRIBUTORS.md` where the all-contributors-spec is implemented.
