### ISSUE TITLE
Ditch the development branch

### ISSUE THREAD

**Issue by Bastian** [Javacord/Javacord#560]
We should reconsider if we really want to keep the `development` branch or just work directly on `master`. Thanks to @Vampire our build-pipeline already fully support this (please correct me if I am wrong).

**Comment by KILLEliteMaste** [comment]
Are there any (dis)advantages when switching to master?

**Comment by Vampire** [comment]
I don't remember what your reasons were for preferring to work on `development`, whether it was influenced by `git-flow`, or whether you simply wanted the latest released state on `master` or whether you wanted to have the possibility to bring out a fast fix for `master` even if `development` is not in a releasable state.

The build-pipeline though is tailored to the branching model you selected, including a build failure if you try to release from anything besides `devlopment`, the automatic branch and PR creation to get the new version to `master` and TeamCity automatically publishing SNAPSHOT version from `development`.

It is not much work to change this to any other branching model you happen to prefer now though. Just a few small changes in the build scripts and TeamCity configuration.

Just reconsider and tell me what you want when you are finished, I don't have strong feelings here.

**Comment by Bastian** [comment]
"Fixed" in https://github.com/Javacord/Javacord/pull/769
