### ISSUE TITLE
Trojan:Java/Tisifi.c in 3.0.6 release

### ISSUE THREAD

**Issue by NomadicCode** [Javacord/Javacord#572]
Upon downloading the javadocs for javacord, Windows Defender treated the javadocs as a trojan.

![virus](https://user-images.githubusercontent.com/64012987/83527553-88bc5c80-a51a-11ea-9d80-ec8fc164dfea.png)

I'm pretty sure this is a false positive, but I wanted it to be acknowledged.

**Comment by Vampire** [comment]
Besides that you shouldn't use the core-classes anyway. :-D
You could upload the file you downloaded to virustotal.com and let all the checkers run.
I downloaded the file from the GitHub release as you did and sent it up and none of the checkers thought it find anything: https://www.virustotal.com/gui/file/5938ced3fd1a02e64dd6360d1175db0e3315f57b32dcb00b7759892e3054fb40/detection
But maybe - even if unlikely - you are target of a man-in-the-middle attack, so upload your version of the file and see if there is a difference.
If not - which I assume - you should report the false-positive to Defender.

**Comment by NomadicCode** [comment]
Ok, I scanned the files using virustotal, all engines didnt detect it: https://www.virustotal.com/gui/file/cbff499db5c8494d42d5e25f8d2e2d5bd4936c3b426846c7806ca41b2a7e4543/detection
Guess, it's a false positive
