### ISSUE TITLE
Suppress logger messages?

### ISSUE THREAD

**Issue by aekramer** [Javacord/Javacord#581]
In my setup I am already using java.util.logging.Logger, so I'd prefer not to add a Log4j library solely for this.

When the discord api is created, it will always print this info message:
"2020-06-27 15:29:37.130+0200 INFO org.javacord.core.util.logging.ExceptionLoggerDelegateImpl No Log4j2 compatible logger was found. Using default Javacord implementation!"

I understand there is no harm done and it is purely informing me, but could this message be suppressed somehow? I feel it clutters up the boot logs

**Comment by Vampire** [comment]
I would recommend you to use log4j for logging, it is so much better to use, better to configure, feature rich, ....
But if you prefer to use JUL as your logging framework that is fine too.
Just add `org.apache.logging.log4j:log4j-to-slf4j` and `org.slf4j:slf4j-jdk14` artifacts to your runtime dependencies.
The first one will forward all log4j usages to slf4j and the second will forward all slf4j usages (including the forwarded) to JUL.
Then you get all log4j and slf4j messages forwarded to JUL and then can configure there what messages you want to get.

**Comment by Bastian** [comment]
Thanks for the suggestion. However, as Vampire said, it's highly recommended to use a proper logging framework.
Vampire provided a lightweight suggestions to solve this problem.
