### ISSUE TITLE
Sending Embedded messages only works in private chat?

### ISSUE THREAD

**Issue by aekramer** [Javacord/Javacord#582]
Hi, I've created an embed with just a title/description and custom color. When I use the command in a private (1 on 1) chat with the bot it works just fine. If I do it in a public server it won't respond (yes the bot has access rights, doing a "normal" message sends just fine).

Example code:
```
general.sendMessage("Hello this is a test message");
```
will work just fine

But:
```
new MessageBuilder()
        .setEmbed(new EmbedBuilder()
             .setTitle("[Owner] Alex")
             .setDescription("Wow this is super fancy!")
             .setColor(Color.MAGENTA))
	 .send(general);
```
wont send

So additionally, I added this command for testing:
```
if (event.getMessageContent().equalsIgnoreCase("!yell")) {
    new MessageBuilder()
		.setEmbed(new EmbedBuilder()
			.setTitle("[Owner] Alex")
			.setDescription("Wow this is super fancy!")
			.setColor(Color.MAGENTA))
		.send(event.getChannel());
}
```
When used in a public channel it won't respond, but in private (dms) it will.

However, this will work just fine in public and private.
```
if (event.getMessageContent().equalsIgnoreCase("!yell2")) {
	event.getChannel().sendMessage("[Owner] Alex: New phone who dis?");
}
```

Are embedded messages not supported in groups/servers? I can't find anything on this so I am assuming it should work.
Am I missing additional privileges for the bot? Are they not the same as normal text messages?

**Comment by Joshix-1** [comment]
Try giving your bot following permission: 
![image](https://user-images.githubusercontent.com/57299889/85945974-c9986d00-b930-11ea-95d0-eb82164d6fd5.png)

You should also handle the exceptions. Add `.exceptionally(ExceptionLogger.get())` to the lines where you send the messages.

**Comment by aekramer** [comment]
> Try giving your bot following permission:
> ![image](https://user-images.githubusercontent.com/57299889/85945974-c9986d00-b930-11ea-95d0-eb82164d6fd5.png)
> 
> You should also handle the exceptions. Add `.exceptionally(ExceptionLogger.get())` to the lines where you send the messages.

Thanks for the quick response, I'll try adding the exception logger.
As for the permissions, these are the permissions the bot has now (although at first embed links wasn't enabled, to enable more permissions do I need to remove the bot from the server first? I just re-invited it with more permissions)

These are all the active permissions now:
https://imgur.com/a/kj7tAxz

**Comment by Joshix-1** [comment]
Update the permissions of the bots role, or re-invite the bot. Also this isn't meant for support. Please join https://discord.gg/0qJ2jjyneLEgG7y3 and ask in #javacord-help.
