### ISSUE TITLE
Reaction Remove Handler incorrectly assumes that users are cached

### ISSUE THREAD

**Issue by Pepich** [Javacord/Javacord#596]
In the [MessageReactionRemoveHandler](https://github.com/Javacord/Javacord/blob/029384adbfb7a1ea8a15870ef549008e68fe8096/javacord-core/src/main/java/org/javacord/core/util/handler/message/reaction/MessageReactionRemoveHandler.java#L37), Javacord assumes that a user removing a reaction must be cached. However given the following scenario, an uncached user can remove a reaction:

- User "user" reacts to a message
- "user" leaves the guild in which the reaction happened
- "user" is removed from the cache by whichever means, e.g. restarting the bot will force this to happen
- A different user "admin" who has "manage message" permissions removes the reaction made by "user"

Discord will now fire a "ReactionRemoveEvent", with the "user_id" field containing the id of "user" and not "admin", resulting in an AssertionError

**Comment by Bastian** [comment]
Thank you for reporting.
Our next but one release will add support for disabling the user cache completely, which will require a larger rewrite.
This will most likely fix this bug as a by-product.
