### ISSUE TITLE
shutdown hook should be controlled with a flag

### ISSUE THREAD

**Issue by Klotzi111** [Javacord/Javacord#601]
**General:**
As you can see in code linked below in case of a successfull instanciation of class DiscordApiImpl a shutdown hook is added that later disconnects the connection. Since shutdown hooks have no execution order this introduces a problem with other shutdown hooks.
https://github.com/Javacord/Javacord/blob/c770bfd99899bdb85b01530eeb186dd59a0eb239/javacord-core/src/main/java/org/javacord/core/DiscordApiImpl.java#L574-L585

**Example:**
In my case I have a custom shutdown hook that uses the discord connection and then disconnects it using the disconnect() method. But the shutdown hook added in the DiscordApiImpl class gets executed before my hook and thus making the connection unusable.

**Solution:**
To resolve this issue a flag (parameter) indicating whether or not this shutdown disconnect hook should be added is needed.
You could add it in the class DiscordApiBuilder or at least give a static field that controls that.

**Alternative (do not fix it):**
1. Manually remove the shutdown hook via reflection after the DiscordApiImpl instance is created
2. Create a new DiscordApiImpl instance (does this even work in a shutdown hook?) and remember all async tasks that have not yet finished and do them again

**Comment by Bastian** [comment]
Thank you for reporting!
I agree with your proposed solution to make it configurable in the API builder.

**Comment by Vampire** [comment]
That shutdown hook is just a last resort fallback. Shutdown hooks generally are not guaranteed to be executed, for example if process is killed or if other shutdown hooks needed too long to execute.

It is the responsibility of the bot developer to call disconnect and that hook as just a last resort fallback if he didn't.

Imho it would be better if the bot would not leverage shutdown hooks to do things, but uses normal code, especially if remote requests need to be done, as shutdown hooks should be as fast as possible.

**Comment by Klotzi111** [comment]
I totally agree with you. This shutdown hook could be removed entirely since discord has no problem with you or your bot account if you simply terminate the connection. Which also happens if you kill the process.

**Comment by Vampire** [comment]
I said the opposite. The bot code should not leverage shutdown hooks as they are inreliable and must not take long like doing remote calls, or even worse if those are done asynchronously, as then it is likely they are not executed anymore.

Javacords hook is fine as it is just a fallback if the bot developer did not properly call disconnect. If you don't do a graceful shutdown, Discord is not notified the bot is down and thus shows it online when it is not. So it is better to try to do an orderly shutdown even if the bot developer forgot to do it properly.

**Comment by Klotzi111** [comment]
Sorry for misunderstanding you.
I write a extension for a library. This library has its cleanup routine in a shutdown hook and so my code's resources get cleaned up at that point too. Since shutdown hooks also get executed if the JVM exits normally (if the main method returns) and I use javacord to send messages to discord asynchronously, I have to wait for those messages to be sent before allowing the JVM to terminate. I know that shutdown hooks should finish their work fast because the process might get killed if it takes too long during a system shutdown. But also in this case I want to send as many messages I can before the JVM gets terminated.
If the JVM terminates and the discord connection is not disconnected then discord shows the bot "online" as you said. But the discord connection uses heartbeat messages to ensure the other end is still alive and if a heartbeat is missing the bot shows as "offline" again (which might take a minute or so depending on the heartbeat interval).

**Comment by Vampire** [comment]
While I still think a shutdown hook is the wrong place for such actions maybe another approach would be better and more useful also in other situations.

What I have in mind is a pre-disconnect listener, so that you can do last actions there.

**Comment by Klotzi111** [comment]
Maybe "a shutdown hook is the wrong place for such actions" but in my case I can not change it. The library I extend would need to.

However I like the idea of a "pre-disconnect listener". But again, not applicable in my case.

An additional neat feature would be a function similar to "disconnect()" maybe call it "awaitAllActionsAndDisconnect" which as the name suggests waits for all pending async tasks associated with the discord connection to complete before disconnecting the connection.
Because without such a await method the bot code needs to keep track of the actions it starts and those that have already completed and await them manually.
Or seperate it in two methods "awaitAllActions(Duration)" and the old "disconnect()".
One might create a new issue with this idea and label it feature request.

**Comment by Bastian** [comment]
https://github.com/Javacord/Javacord/issues/598
There's already an issue for this

**Comment by Vampire** [comment]
Why would the pre-disconnect listener not work in your case? Instead of registering a shutdown hook you would register that listener with the difference that its execution is guaranteed to be done before the actual disconnect. You can then either properly call disconnect as you're supposed to, or hope for the shutdown hook to be triggered and in both cases your cleanup code would run.

**Comment by Klotzi111** [comment]
> 
> 
> There's already an issue for this: #598

As far as I understand #598 it asks for a Future (awaitable) for the disconnect action itself.
But what I meant is a method that waits for all Futures that have ever returned by any method of DiscordApi.

> 
> 
> Why would the pre-disconnect listener not work in your case? Instead of registering a shutdown hook you would register that listener with the difference that its execution is guaranteed to be done before the actual disconnect. You can then either properly call disconnect as you're supposed to, or hope for the shutdown hook to be triggered and in both cases your cleanup code would run.

Yea I understud the logic of a pre-disconnect listener. It would actually work but i would need to wait inside the listener for the other (library's) shutdown hook to complete because that shutdown hook might trigger actions that need to be done using the discord connection. And a shutdown hook waiting for an other shutdown hook was not my first thought. Also that would only work if the JVM implementation launches all the shutdown hooks in seperate threads concurrently (not sure if that is always the case).

**Comment by Bastian** [comment]
> As far as I understand #598 it asks for a Future (awaitable) for the disconnect action itself.

Indeed. But with the option to disable the default shutdown hook registration, I don't think such methods will be necessary.

https://github.com/Javacord/Javacord/pull/602 adds the option to disable the shutdown hook registration in the api builder. While there are probably very few (or maybe even no?) use cases for, I don't think it does any harm to have the option. It's definitely faster to implement than a pre-disconnect listener.
