### ISSUE TITLE
Add support for developer teams

### ISSUE THREAD

**Issue by Phoenix616** [Javacord/Javacord#614]
Currently there is no support for getting and handling [developer teams](https://discord.com/developers/docs/topics/teams) in the API. It would be nice to be able to use this e.g. when having an application be owned by a team and still being able to check if a user has certain access rights to it. `User#isBotOwner` fails for obvious reasons if a bot's application is owned by a team.

Either that would check for admin rights in the team itself or `DiscordApi#getOwner` would return an object to check the Team rights. Currently it just returns a user with a `team<id>` name)

**Comment by Joshix-1** [comment]
I wouldn't change `DiscordApi#getOwner`
https://discord.com/developers/docs/topics/oauth2#get-current-application-information-example-application-information calls them members of the team.

**Comment by Phoenix616** [comment]
Well getOwner should still return a usable object (e.g. a Team one which would implement the User one or directly return a "BotOwner" interface) as the current one isn't really helpful for anything.

**Comment by Joshix-1** [comment]
Why isn't it helpful? It gets the full User Object, with everything you need and get from Discord.

**Comment by Bastian** [comment]
I agree with Joshix. The `#get/isOwner()` method shouldn't change.

If I see it correctly, a new `User#isTeamMember()` and `DiscordApi#getTeam()` should be the way to go.

**Comment by Phoenix616** [comment]
I still feel that returning a proper Team object there which can be acted on would be more useful (as it would avoid doing additional queries with the Owner's ID just to get the Team) or at least an `AccountType.TEAM` (as it clearly isn't a `AccountType.User` like the API currently claims) so that one doesn't have to check if the name starts with `team` (something that could be abused).

**Comment by Joshix-1** [comment]
I would return a Team Object as well. But not as you described. I will make a draft PR with the basics and then we can discuss about that and improve it.
