### ISSUE TITLE
Update jackson-databind

### ISSUE THREAD

**Issue by Phoenix616** [Javacord/Javacord#651]
Javacord is currently using jackson 2.9.3 while the latest is 2.12 which leads to incompatibilities with other programs libraries that also use that but more updated versions.(e.g. twitch4j)

Would be cool to have that fixed here so that one doesn't need to manually (and somewhat blindly) shade an updated version and hope it works.

**Comment by KILLEliteMaste** [comment]
Closed because of a more general issue #807
