### ISSUE TITLE
Bot takes 2+ Minutes to connect!

### ISSUE THREAD

**Issue by hesperiusproject** [Javacord/Javacord#663]
Hello, I recently started adding new features to by bot, and, after compiling the code, I notice it took over 2 minutes to connect. I'm fairly certain that this issue is due to Javacord.

Is there a solution to this problem?

**Comment by CPLShiv** [comment]
The newest version of Javacord requires you to enable specific Intents for certain events; the GUILDS intent is required always, so make sure you enable that. See more here: https://javacord.org/wiki/basic-tutorials/gateway-intents.html and documentation for setting them here: https://docs.javacord.org/api/v/3.1.1/org/javacord/api/DiscordApiBuilder.html#setIntents-org.javacord.api.entity.intent.Intent...-

**Comment by hesperiusproject** [comment]
Thank you very much, it has indeed fixed my issue!
