### ISSUE TITLE
.getMembers() doesn't return all server members

### ISSUE THREAD

**Issue by theLucy** [Javacord/Javacord#664]
I tried returning collection of all server members and it only returned bot itself or me.
I tried to return users of particular role, but no luck too.
getMemberCount() returns total amount of users. So why can't i get all users themselves? Do I get this usage wrong or is this a bug?

**Comment by ShindouMihou** [comment]
Do you have the proper intents activate?
`GUILD_MEMBERS`

**Comment by ShindouMihou** [comment]
> I tried returning collection of all server members and it only returned bot itself or me.
> I tried to return users of particular role, but no luck too.
> getMemberCount() returns total amount of users. So why can't i get all users themselves? Do I get this usage wrong or is this a bug?

Also, in response to particular role members, there is a bug in regards to that.

I think Issue #660 talks about the issue.

**Comment by theLucy** [comment]
Oh this is my bad, indeed, i have intent enabled on developer site but i now find this:
https://javacord.org/wiki/basic-tutorials/gateway-intents.html#setting-intents
so its just my error, well thanks for fast help! ^^
