### ISSUE TITLE
EmbedBuilder.setColor(Color.WHITE) uses dark grey instead of white

### ISSUE THREAD

**Issue by MarvinSkilla** [Javacord/Javacord#670]
**Current Behaviour**
Passing `new Color(255,255,255)` or `Color.WHITE` to`new EmbedBuilder().setColor()` results in a dark grey color. Using `new Color(254,255,255)` or `new Color(255,254,255)` or `new Color(255,255,254)` seems to circumvent this bug.

**Expected Behaviour**
Passing `new Color(255,255,255)` or `Color.WHITE` to`new EmbedBuilder().setColor()` results in a white embed color.

**JavaCord version:** 3.1.1
**Java version:** 1.8.0_231

**Comment by Vampire** [comment]
When will you learn to stop calling Javacord JavaCord?

Besides that, Javacord just forwards the color to Discord.
Even Discord just forwards the color as it is to the client (double-checked in Network tools of the Browser).
The Discord client decides to display white as the default color which in the dark theme is 0x202225.
If you want this fixed, you need to report it to Discord.
Imho Javacord should not employ some work-around here.

**Comment by MarvinSkilla** [comment]
Thank you for your clarification. Is there a fixed list of color codes which are displayed differently in dark mode?

**Comment by Vampire** [comment]
Ask Discord

**Comment by Bastian** [comment]
Thanks for the bug report! Like @Vampire said, there's not much we can do because this is a Discord ~bug~ limitation.
I've created a new issue to improve the documentation of the methods to mention this behavior: https://github.com/Javacord/Javacord/issues/676
