### ISSUE TITLE
Support interactions

### ISSUE THREAD

**Issue by KILLEliteMaste** [Javacord/Javacord#672]
Discord has just merged this new feature which adds slash commands to interact with bots(or sent via webhook)
https://discord.com/developers/docs/interactions/slash-commands

### Slash commands
* [x] Receiving interactions
* [x] Creating interactions
* [x] Deleting interactions
* [x] Get global interactions
* [x] Get guild application commands
* [x] Update existing application commands
* [x] Respond to application commands
* [x] Bulk overwrite guild application commands
* [x] Implement Slash Command Permissions
* [x] Add convenience methods (e.g., for extracting simple options without having to use the Java streaming api).
* [x] Wiki Documentation
* [x] README example

### Components
* [x] Action rows
* [x] Buttons
* [x] Respond to component interaction

**Comment by KILLEliteMaste** [comment]
There are some changes to Slash Command Response Types and Flags
https://github.com/discord/discord-api-docs/blob/master/docs/Change_Log.md#changes-to-slash-command-response-types-and-flags

**Comment by coaxial1** [comment]
Can we close this?
