### ISSUE TITLE
Changing nickname & profile pic per message?

### ISSUE THREAD

**Issue by skerit** [Javacord/Javacord#673]
I've seen a certain Discord group use a bot as a minecraft bridge. Each message sent in Minecraft would be sent to the Discord channel.

This part is easy to do with Javacord, but it had a nice extra: it changed the nickname & profile picture of each message. It looked like this:

![afbeelding](https://user-images.githubusercontent.com/755212/102386843-ece2d180-3fcf-11eb-8e0d-73629c9b4da5.png)

Each message looks like it's from a different player, but it's the same bot each time. Is there a way I can do this with the MessageBuilder somehow?

**Comment by Bastian** [comment]
These are most likely not send with a "regular" bot but with a webhook instead. Webhooks allow you to set an avatar and display name. You can add webhooks to channels with Javacord like shown in our wiki: https://javacord.org/wiki/basic-tutorials/creating-entities.html#create-webhooks

Sending messages to webhooks is currently not supported by Javacord but you can use an external library like https://github.com/MinnDevelopment/discord-webhooks to do it. There's also an open PR that adds this fucntionality directly to Javacord itself: https://github.com/Javacord/Javacord/pull/573

**Comment by skerit** [comment]
Thanks for the info!

**Comment by Bastian** [comment]
You're welcome :)
