### ISSUE TITLE
java.lang.IllegalStateException: No DelegateFactoryDelegate implementation was found!

### ISSUE THREAD

**Issue by SirLennox** [Javacord/Javacord#677]
Hello, I was trying to create a discord bot.
In my IDE it worked fine but as I exported it there was an error:
```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.javacord.api.DiscordApiBuilder.<init>(DiscordApiBuilder.java:33)
	at me.sirlennox.selfy.Selfy.buildBot(Selfy.java:40)
	at me.sirlennox.selfy.Selfy.<init>(Selfy.java:35)
	at me.sirlennox.selfy.Main.main(Main.java:22)
Caused by: java.lang.IllegalStateException: No DelegateFactoryDelegate implementation was found!
	at org.javacord.api.util.internal.DelegateFactory.<clinit>(DelegateFactory.java:74)
	... 4 more
```

I hope you can help me, thanks :)

**Comment by SirLennox** [comment]
I tried it with maven and gradle (Build > Build Artifact > Build)

**Comment by ShindouMihou** [comment]
Do you mind showing some code snippets?

**Comment by SirLennox** [comment]
yes
```java
 this.API = addEventListeners(buildBot(token));
 
 
 
public DiscordApi addEventListeners(DiscordApi api) {
        api.addMessageCreateListener(event -> {
            if(event.getMessage().getAuthor().getId() == api.getYourself().getId()) {
                String msg = event.getMessageContent();
                if(msg.startsWith(PREFIX)) {
                    String msgWithoutPrefix = msg.substring(PREFIX.length());
                    String[] args = new String[msgWithoutPrefix.split(" ").length - 1];
                    for(int i = 1; i < msgWithoutPrefix.split(" ").length; i++) {
                        args[i - 1] = msgWithoutPrefix.split(" ")[i];
                    }
                    String c = msgWithoutPrefix.split(" ")[0];
                    for(Command cmd : this.commandManager.commands) {
                        if(cmd.cmd.equalsIgnoreCase(c) || isAliasOfCommand(cmd, c)) {
                            if(cmd.onlyPremium && !Utils.hasAccessToPremiumFeatures()) {
                                MessageUtils.editMessage("Error", "This command is premium only and you don't have premium!", Color.RED.getRGB(), event.getMessage());
                                return;
                            }
                            cmd.onCommand(args, event);
                            return;
                        }
                    }
                }
            }
        });
        return api;
    }
    
    
    public DiscordApi buildBot(String token) {
        return new DiscordApiBuilder().setAccountType(AccountType.CLIENT).setToken(token).login().join();
    }
 ```

**Comment by Vampire** [comment]
You probably try to build a fat jar and do it wrongly, which is one of the reasons fat jars are evil.
You miss the javacord-core artifact in your fat jar, or at least the relevant files from `META-INF`.
As you mentioned Gradle, I'd strongly recommend building a proper distribution instead, by applying the `application` plugin. Then (and after configuring the main class properly) you can use `distTar` or `distZip` to create a distributable archive with everyting you need and nifty start scripts in the `bin` directory of that archive.

**Comment by SirLennox** [comment]
I have javacord-core and in my META-INF is only a MANIFEST.MF

**Comment by SirLennox** [comment]
so is this wrong?

**Comment by Vampire** [comment]
Yes, that is wrong

**Comment by Vampire** [comment]
Btw. you are trying to build a self-bot, that is a violation of the Discord ToS, will in near future removed from Javacord completely and is already broken in large parts already due to incompatible changes on Discord side.

**Comment by SirLennox** [comment]
Ok, and what do I have to put into my META-INF?

**Comment by Vampire** [comment]
The javacord-core artifact has files in there in `services` that are essential.
If you repack the artifact but leave out those files, you should not wonder that it does not work.
That's one of the reasons fat jars are evil, you are modifying libraries in unsupported ways and then go to the maintainers and complain that their library does not work, while you actively broke it by manipulating the files. ;-)

**Comment by SirLennox** [comment]
Thank you very much, it worked fine. Please stay supporting selfbots, because there aren't any java libraries with selfbot support, and I like java (I don't want to switch to python) :)
