### ISSUE TITLE
Streaming not recognized properly with custom status

### ISSUE THREAD

**Issue by IKanraI** [Javacord/Javacord#691]
Purple streaming on profile is not recognized when a status update happens.

In the words of Vampire: 
"The PRESENCE_UPDATE has a game field and an activities field.
The game is what is also shown as status in the client and is what we return on getActivity and what the event is fired about.
The activities is an array where your custom status and your twitch streaming is contained, but Javacord does not currently evaluate that field, I guess it is something new." -- Vampire

He also explained that javacord only evaluates game and ignores the activities

Javacord version: 3.1.2

**Comment by coaxial1** [comment]
I think the ``game``field is only populated for legacy v6 API clients. It has been removed and superceded by the activities array in v8, so we need to switch anyways.
https://discord.com/developers/docs/change-log#api-and-gateway-v8

(ping: #642 #679 )

**Comment by Vampire** [comment]
Here an example presence update packet:
```json
{
    "user": {
        "id": "150415472028811264"
    },
    "status": "dnd",
    "roles": [],
    "guild_id": "151037561152733184",
    "game": {
        "type": 4,
        "state": "Take your time",
        "name": "Custom Status",
        "id": "custom",
        "emoji": {
            "name": "TakeYourHeart",
            "id": "527614410399809537",
            "animated": true
        },
        "created_at": 1609858220533
    },
    "client_status": {
        "desktop": "dnd"
    },
    "activities": [
        {
            "type": 4,
            "state": "Take your time",
            "name": "Custom Status",
            "id": "custom",
            "emoji": {
                "name": "TakeYourHeart",
                "id": "527614410399809537",
                "animated": true
            },
            "created_at": 1609858220533
        },
        {
            "url": "https://www.twitch.tv/ikanrai",
            "type": 1,
            "state": "Just Chatting",
            "name": "Twitch",
            "id": "d08825724ef4edc6",
            "details": "testing2dfgbhnm,",
            "created_at": 1609861631992,
            "assets": {
                "large_image": "twitch:ikanrai"
            }
        }
    ]
}
```
