### ISSUE TITLE
Optional<ActivityAssets> is always empty.

### ISSUE THREAD

**Issue by moeux** [Javacord/Javacord#695]
I must say the documentation on `ActivityAssets` leaves one in the dark, including even Discord's: https://canary.discord.com/developers/docs/game-sdk/activities
I can't seem to find a clear definition of what assets are.

```java public void onUserChangeActivity(UserChangeActivityEvent event) {
        event.getNewActivity().ifPresent(activity -> {
                activity.getAssets().isPresent() // FALSE
```
This leads me to believe that this might be bug, if my assumption that the screenshot below is representative of `ActivityAssets`, is true.
![image](https://user-images.githubusercontent.com/68925026/104125189-7c706b80-5355-11eb-83c3-fb579dab73dd.png)

**Comment by Bastian** [comment]
This is most likely related to https://github.com/Javacord/Javacord/issues/691 and should be fixed by https://github.com/Javacord/Javacord/pull/692

**Comment by KILLEliteMaste** [comment]
Just to clarify this:
![image](https://user-images.githubusercontent.com/31566807/114270151-16a28700-9a0b-11eb-8cc6-6eaa062cf0ca.png)
Here is the large_text `Nevermind (Deluxe Edition)` and large_image `spotify:ab67616d0000b27328a90d00a2819504364880e4` set in the ActivityAssets.
