### ISSUE TITLE
Allow sorting of roles

### ISSUE THREAD

**Issue by Laarryy** [Javacord/Javacord#710]
Docs regarding role sorting: https://discord.com/developers/docs/resources/guild#modify-guild-role-positions 

It would be excellent to be able to sort roles via integer in role list, and perhaps even by a role ID matcher (loop through role IDs, get the integer of the role with provided ID) so that relative positions are possible, such as `booster role` +1

**Comment by Vampire** [comment]
What exactly are you asking for here? You can already updated order of roles with Javacord using `reorderRoles` and the list you get can be used to get the "next bigger role" / "next lower role".

**Comment by Laarryy** [comment]
Thanks Vampire, just couldn't find reorderRoles when I was looking :smile:
