### ISSUE TITLE
Server#getMembers() not returning all members immediately after a serverJoinEvent

### ISSUE THREAD

**Issue by elainecao93** [Javacord/Javacord#717]
This used to work properly prior to 3.1.0 update, but hasn't worked for a while and I never got around to reporting it.

Using v3.1.2 with GUILD_MEMBERS intent

Expected:

`serverJoinEvent.getServer().getMembers()` returns all members in server

Actual:

`serverJoinEvent.getServer().getMembers()` returns only the user that added the bot to the server

The function returns properly after a delay (not sure how long) but I find it very strange that it does not work immediately.

Not breaking anything significant at least for me, just wanted to make you aware of it.

**Comment by KILLEliteMaste** [comment]
> The function returns properly after a delay
Is the event immediately called after the bot started? If so depending on the amount of guilds and its users your bot is in, it needs some time to fetch all users and add them to the cache after logging in.

**Comment by elainecao93** [comment]
The function is called immediately after joining a server, not when the bot starts.

Is there a reason why it takes a while to fetch the users now? It used to work instantly.

**Comment by Vampire** [comment]
Necessary changes due to intents

**Comment by Vampire** [comment]
You probably need to wait until the list is `Server#getMemberCount()` in size

**Comment by elainecao93** [comment]
Alright. Figured it was worth a shot.
