### ISSUE TITLE
ServerMemberJoinListener not working

### ISSUE THREAD

**Issue by dlite2** [Javacord/Javacord#719]
Hi,

I've implemented a bot for my little server yet. As assumed by the JavaDoc-Page, this listener should trigger events on new users joining the server. We've tested this on an invitelink, but the listener is never triggered.

Is there a bug maybe in the implementation of this listener?

I'm using this version in my gradle-project: 	implementation 'org.javacord:javacord:3.1.2'

It should be mentioned, that the bot was invited and got administration intents.

**Comment by ShindouMihou** [comment]
Hello, do you have the intent: `GUILD_MEMBERS` enabled since that particular event requires it.

If you do have it enabled on both code and dashboard then please show your listener code for us to have an understanding of the issue, otherwise, please check the wiki, in particular, the part that says Gateway Intents for more information.

**Comment by dlite2** [comment]
Hi,

i'd used your hint to set the intents, but that doesn't work either.

I'm using Springboot as Backendservice and adding a bot there, so there is a bit of Spring magic in the following code.

The first is the creation of my bot-bean. That bean is as singleton implemented and held in Spring Boot:

```
String botToken = pageConfig.getDiscord().getBotToken();
DiscordApi api = new DiscordApiBuilder()
		                    .setToken(botToken)
		                    .login()
                                    .join();
		
Permissions perms = new PermissionsBuilder().setAllowed(PermissionType.values()).build();
System.out.println("Botinvite: " + api.createBotInvite(perms));
return api;
```

The login works, the code I get via Invite works as well and my bot is joining on my server.

Now I think, as I add a listener for join-events like the Discord-own bot does with its "Hello guy" messages, I could react to these events, too.

That happen in this snippet on the previous created api-bean:

```
discordApi.addServerMemberJoinListener(event -> {
	String discrimname = event.getUser().getDiscriminatedName();
	System.out.println("User ServerMemberJoinEvent joined: " + discrimname);
});
```

But this listener is never fired. Is my expectation wrong at this point? 
I just want to react, if someone is joining on the server.

On the other hand, the addMessageCreateListener works as expected.

**Comment by dlite2** [comment]
I've tought, I had all intents set. The solution is found. Thanks for the hint. It should be 

```
DiscordApi api = new DiscordApiBuilder()
                                    .setAllIntents()
		                    .setToken(botToken)
		                    .login()
                                    .join();
		
```

so the bot can listen to all events.
