### ISSUE TITLE
MessageCreateEvent does not trigger upon messages being sent in DMs

### ISSUE THREAD

**Issue by elainecao93** [Javacord/Javacord#732]
Breaking bug in 3.2.0.

Using the example bot in the `readme.md`:

Expected behavior: When the bot is interacted with in DMs, the bot replies in DMs.

Actual behavior: The bot does not reply because the `MessageCreateEvent` does not trigger.

**Comment by Vampire** [comment]
Duplicate of #707

**Comment by Bastian** [comment]
I've just released version 3.3.0 that fixes this bug.
