### ISSUE TITLE
Javacord bot fails to play audio in a voice channel.

### ISSUE THREAD

**Issue by Macintosh-Fan** [Javacord/Javacord#754]
When I run my command to join the voice channel and play audio then disconnect, I get this error:
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2021-05-23 15:01:34.429-0700 INFO org.javacord.core.util.gateway.AudioWebSocketAdapter Websocket closed with reason 'unknown' and code NORMAL (1000) by client for AudioConnection (channel: ServerVoiceChannel (id: 760350712353259543, name: General), sessionId: d41a8cfc709285063c6ae30a34dd9806, endpoint: us-west7144.discord.media:443)! {shard=0} 
2021-05-23 15:01:34.498-0700 WARN org.javacord.core.util.handler.guild.VoiceStateUpdateHandler Couldn't get the Channel with the id 0 for a org.javacord.core.util.handler.guild.VoiceStateUpdateHandler. Please update to the latest Javacord version or create an issue on the Javacord GitHub page if you are already on the latest version. {shard=0}
```

Code:
```
ServerVoiceChannel sVC = event.getApi().getServerVoiceChannelById(760350712353259543L).get();
sVC.connect().thenAccept(audioConnection -> {
    // Create a player manager
    AudioPlayerManager playerManager = new DefaultAudioPlayerManager();
    playerManager.registerSourceManager(new YoutubeAudioSourceManager());
    AudioPlayer player = playerManager.createPlayer();

    // Create an audio source and add it to the audio connection's queue
    AudioSource source = new LavaPlayerAudioSource(event.getApi(), player);
    audioConnection.setAudioSource(source);

    // Use AudioPlayer like normal LavaPlayer
    playerManager.loadItem("https://youtu.be/YAPzjHObF1A", new AudioLoadResultHandler() {
        @Override
        public void trackLoaded(AudioTrack track) {
            player.playTrack(track);
        }

        @Override
        public void playlistLoaded(AudioPlaylist playlist) {
            for (AudioTrack track : playlist.getTracks()) {
                player.playTrack(track);
            }
        }

        @Override
        public void noMatches() {
            event.getChannel().sendMessage("No matches :(");
        }

        @Override
        public void loadFailed(FriendlyException exception) {
            event.getChannel().sendMessage("Load failed :(");
        }
    });
    audioConnection.close();
});
```

**Comment by shuen4** [comment]
`audioConnection.close();`

> Disconnects from the voice channel.

https://github.com/Javacord/Javacord/blob/f825905377ee30f8614190aef55da0e6b629da7f/javacord-api/src/main/java/org/javacord/api/audio/AudioConnection.java#L33

**Comment by Macintosh-Fan** [comment]
> `audioConnection.close();`
> 
> 
> 
> > Disconnects from the voice channel.
> 
> 
> 
> https://github.com/Javacord/Javacord/blob/f825905377ee30f8614190aef55da0e6b629da7f/javacord-api/src/main/java/org/javacord/api/audio/AudioConnection.java#L33-L40

@shuen4 What do you mean by that?

**Comment by shuen4** [comment]
> > `audioConnection.close();`
> > 
> > 
> > 
> > > Disconnects from the voice channel.
> > 
> > 
> > 
> > https://github.com/Javacord/Javacord/blob/f825905377ee30f8614190aef55da0e6b629da7f/javacord-api/src/main/java/org/javacord/api/audio/AudioConnection.java#L33-L40
> 
> @shuen4 What do you mean by that?

this mean bot disconnects from voice channel so it can't play audio anymore

**Comment by ShindouMihou** [comment]
I'll explain it better in his/her place, he/she means your code is triggering `AudioConnection#close` after selecting a song which basically closes the audio connection between your bot and Discord which in turns makes your bot leave.

The `close` method is located at the end of the excerpt code you showed.

**Comment by Macintosh-Fan** [comment]
> I'll explain it better in his/her place, he/she means your code is triggering `AudioConnection#close` after selecting a song which basically closes the audio connection between your bot and Discord which in turns makes your bot leave.
> 
> The `close` method is located at the end of the excerpt code you showed.

@ShindouMihou Then where should I run the close method? Because I can't use thenRun() since the loadItem() method does not have thenRun().

**Comment by ShindouMihou** [comment]
> > I'll explain it better in his/her place, he/she means your code is triggering `AudioConnection#close` after selecting a song which basically closes the audio connection between your bot and Discord which in turns makes your bot leave.
> > The `close` method is located at the end of the excerpt code you showed.
> 
> @ShindouMihou Then where should I run the close method? Because I can't use thenRun() since the loadItem() method does not have thenRun().

You can add a command like `leave` or `disconnect` that will disconnect the bot from the voice channel, or if you want it to leave after the track finishes (obviously after checking if there is any new tracks after) then please take a look at `TrackScheduler` which is a LavaPlayer thing.

https://github.com/sedmelluq/lavaplayer/blob/master/demo-jda/src/main/java/com/sedmelluq/discord/lavaplayer/demo/jda/TrackScheduler.java

You also obviously have to mess around with the `TrackScheduler` code to have it support for it. There are many other ways to doing it.

Anyhow, your code runs like this basically (synchronous):
`Connect to Voice Channel` -> `Setup Audio` -> `Fetch data from YouTube` -> `Process then go through AudioLoadResultHandler` -> `Disconnect from Voice Channel`.

**Comment by Macintosh-Fan** [comment]
How would I fetch the voice channel and know how to disconnect?

**Comment by ShindouMihou** [comment]
> How would I fetch the voice channel and know how to disconnect?

You have `Server#getAudioConnection` for that, if you are using it on `TrackScheduler`, write **modifications** to it to have the server id added already to the `TrackScheduler` then you can easily fetch the Server through the `DiscordApi`.

**Comment by shuen4** [comment]
`if (event.getMessageContent().toLowerCase().startsWith("!play ")) {
    ServerVoiceChannel sVC;
    // If user inside a voice channel
    if (event.getMessageAuthor().asUser().isPresent()&&event.getMessageAuthor().asUser().get().getConnectedVoiceChannel(event.getServer().get()).isPresent())
        // Join user current voice channel
        sVC=event.getMessageAuthor().asUser().get().getConnectedVoiceChannel(event.getServer().get()).get();
    else
        // Join voice channel id 760350712353259543
        sVC=event.getApi().getServerVoiceChannelById(760350712353259543L).get();
    // Connect voice channel
    sVC.connect().thenAccept(audioConnection -> {
        // Load result
        CompletableFuture<AudioSource> future = new CompletableFuture<>();
        // YouTube url
        String url = event.getMessageContent().substring(6);
        // Create a player manager
        AudioPlayerManager playerManager = new DefaultAudioPlayerManager();
        playerManager.registerSourceManager(new YoutubeAudioSourceManager());
        AudioPlayer player = playerManager.createPlayer();
        // Use AudioPlayer like normal LavaPlayer
        playerManager.loadItem(url, new AudioLoadResultHandler() {
            @Override
            public void trackLoaded(AudioTrack track) {
                player.playTrack(track);
                // Create an audio source
                future.complete(new YouTubeAudioSource(api, player, playerManager.getFrameBufferDuration(), url));
            }
            // Not tested
            @Override
            public void playlistLoaded(AudioPlaylist playlist) {
                for (AudioTrack track : playlist.getTracks()) {
                    player.playTrack(track);
                }
                // Create an audio source
                future.complete(new YouTubeAudioSource(api, player, playerManager.getFrameBufferDuration(), url));
            }
            // Not tested
            @Override
            public void noMatches() {
                event.getChannel().sendMessage("No matches :(");
                future.completeExceptionally(new IllegalArgumentException("No matches :("));
            }
            // Not tested
            @Override
            public void loadFailed(FriendlyException exception) {
                event.getChannel().sendMessage("Load failed :(");
                future.completeExceptionally(exception);
            }
        });
        // If load fail
        if (future.isCompletedExceptionally())
            //Disconnect from voice channel 
            audioConnection.close();
        // Load success
        future.thenAccept(source -> {
            // Add it to the audio connection's queue
            audioConnection.setAudioSource(source);
            // When audio source finish
            source.addAudioSourceFinishedListener(audioevent -> {
                // Disconnect from voice channel
                audioevent.getConnection().close();
            });
        });
    });
}`

**Comment by shuen4** [comment]
[code.txt](https://github.com/Javacord/Javacord/files/6680463/code.txt)

**Comment by Macintosh-Fan** [comment]
Well, I did get the audio to successfully play, so it's all good now.
