### ISSUE TITLE
Add issue / PR templates

### ISSUE THREAD

**Issue by KILLEliteMaste** [Javacord/Javacord#767]
To have a more uniform and complete description of issues and PR's we should create templates you can choose from. Any suggestions to improving a template or adding a new one is appreciated. 

My first proposal for a PR template:

---

## Type of change

| ✅ 	| Type 	|
|-	|-	|
|  	| Bug fix (non-breaking change which fixes an issue) 	|
|  	| New feature (non-breaking change which adds functionality) 	|
|  	| Breaking change (fix or feature that would cause existing functionality to not work as expected or changes in the API module) 	|
|  	| Documentation / Typo 	|

## Necessary checks

- [ ] Changes have been tested

## Description

Include a short appropiate description of what the PR changes (which could possibly be taken into the changelog)

**Comment by Vampire** [comment]
I didn't look at it in depth, but generally I'm against a template containing checkboxes from which not all are intended to be checked.
If you have 5 checkboxes and 3 are checked it shows as "3/5 done" which is very misleading if 5/5 will never be reached.

**Comment by KILLEliteMaste** [comment]
> I didn't look at it in depth, but generally I'm against a template containing checkboxes from which not all are intended to be checked.
> If you have 5 checkboxes and 3 are checked it shows as "3/5 done" which is very misleading if 5/5 will never be reached.

Good point, didn't think of that. The only thing we could do is to mention with `Please delete options that are not relevant.` that not checked boxed should be removed. What do you think of that?

**Comment by Vampire** [comment]
Not much actually.
People don't read instructions or don't adhere to them.
You should even put to be replaced texts into HTML comments in the actual template, so that they are not displayed even if users don't delete the texts as they regulary don't and that makes the report even less readable compared to having no template.

**Comment by KILLEliteMaste** [comment]
> Not much actually.
> People don't read instructions or don't adhere to them.
> You should even put to be replaced texts into HTML comments in the actual template, so that they are not displayed even if users don't delete the texts as they regulary don't and that makes the report even less readable compared to having no template.

@Vampire Maybe a more unusual way to do this but what do you think about the table? Otherwise the only other possibility I know of is to comment the PR types out and let the user uncomment them.
The text is going to be comented out and is just for the template visualization visible here 🙂

**Comment by Bastian** [comment]
GitHub now supports form templates: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms

This **might** also help with https://github.com/Javacord/Javacord/issues/1033.
