### ISSUE TITLE
Add multi embed support for bot messages

### ISSUE THREAD

**Issue by KILLEliteMaste** [Javacord/Javacord#772]
Discord now allows bots to send up to 10 embeds per message and therefore gets closer to the webhook behaviour.
https://github.com/discord/discord-api-docs/pull/3105

**Comment by AyuAi** [comment]
Woah .. . this is kind of a game changer for a lot of hefty bot outputs, lol

**Comment by coaxial1** [comment]
LOL. I was asking myself why I've been able to edit a bot message with more than one embed when responding to an interaction with type 7
