### ISSUE TITLE
User info fetching is buggy

### ISSUE THREAD

**Issue by SirLennox** [Javacord/Javacord#825]
I am running a clientside discord bot. I tried to make a userinfo command, but there was an wreird error. I can't get the onlinestatus and client from peoples, who arent since the start of the program in my opened dms. If I opened their DMs later, nothing will change, but if I send them a friend request and they accept, it's working. I tried to get the member from the server throught the user but server.getMembers() just contained 3 players instead of 40.

**Comment by KILLEliteMaste** [comment]
We do not support user bots as they violate the TOS of Discord therefore we are also not interested in finding the cause of bugs related to it.
