### ISSUE TITLE
MessageCreateEvent not working for other people

### ISSUE THREAD

**Issue by SirLennox** [Javacord/Javacord#826]
Hello, 
I am developing a clientside discord bot, but the MessageCreateEvent gives me " " instead of the right message (if the message is from other users) my own messages are working perfectly.

**Comment by ShindouMihou** [comment]
I'm guessing that by 'client-side' discord bot, you are referring to 'user bots' which is violating the TOS of Discord. Javacord has long foregone support for 'client-side' discord bot, otherwise known as 'user bots'. If you are referring to a proper Discord bot then you can disregard this message.

**Comment by SirLennox** [comment]
> I'm guessing that by 'client-side' discord bot, you are referring to 'user bots' which is violating the TOS of Discord. Javacord has long foregone support for 'client-side' discord bot, otherwise known as 'user bots'. If you are referring to a proper Discord bot then you can disregard this message.

Yes I mean the 'user bots' and what should that mean for my question, it looks like a bug in the API.

**Comment by Mysterypotatoguy** [comment]
I don't think it's a bug, more like an intentional feature to prevent user-bots. I've seen this crop up a few times but as already stated we have dropped support for user-bots so there's no interest in finding out why.
