### ISSUE TITLE
Message Content Access becoming a privileged intent

### ISSUE THREAD

**Issue by elainecao93** [Javacord/Javacord#829]
Not sure how this affects api development but I figured changes probably need to be made with this in mind.

https://support-dev.discord.com/hc/en-us/articles/4404772028055

**Comment by coaxial1** [comment]
We can't do much about it except adding the new intent as soon as it's announced.
It won't break anything as message content will just be an empty string and not null or something.

We just need to be quick to implement other interactions that could serve as replacement to message based flows.
