### ISSUE TITLE
MessageUpdater only stores the first embed passed into its constructor

### ISSUE THREAD

**Issue by Alan19** [Javacord/Javacord#836]
When passing in a Message object into MessageUpdater, it only contains the first embed in the embed ArrayList. I can get around this by clearing the embeds from the MessageUpdater, then converting the embeds in the message object into an array and then adding that to the updater.

**Comment by Alan19** [comment]
I'm wondering if this line is the issue as it's only adding one embed even if there's more in the message
https://github.com/Javacord/Javacord/blob/3dc69a9d07b6e2cdfc0d12164c71e7a4fe74791d/javacord-core/src/main/java/org/javacord/core/entity/message/MessageBuilderBaseDelegateImpl.java#L201

**Comment by KILLEliteMaste** [comment]
Thank you for reporting and already investigating on this issue. You are right that this line causes this problem and with that there are also a few more things that weren't adapted correctly to the multiple embed changes. I will push out a PR later that addresses these issues.
