### ISSUE TITLE
Boolean options don't work

### ISSUE THREAD

**Issue by Alan19** [Javacord/Javacord#840]
The boolean option uses the stringValue field to check if it's true or false, but it is null whenever I use booleans in a slash command

**Comment by KILLEliteMaste** [comment]
Yeah you are right. But it wasn't our fault as Discord describes the possible values as follows https://discord.com/developers/docs/interactions/slash-commands#application-command-object-application-command-option-choice-structure 
and it doesn't include boolean so we assumed it would be a string.
