### ISSUE TITLE
Add min_value and max_value for slash command options

### ISSUE THREAD

**Issue by KILLEliteMaste** [Javacord/Javacord#889]
See: https://github.com/discord/discord-api-docs/pull/3967

**Comment by ILGO0413** [comment]
I made a pull request, but it should be discussed probably. 
New min_value and max_value properties should be integer for `INTEGER` options, double for `NUMBER` options according to discord api docs. Therefore I implemented it as a pair of `INTEGER` min/max values (between -2^53 and 2^53, therefore long is used), getters for `INTEGER` values check command option type and throw an UnsupportedOperationException if it is different. `NUMBER` logic can be implemented the same way later (based on double primitive type).
It is probably possible to use only double min/max values, and it would even work for small values, but I am not sure if any issues with double precision can be faced.
