### ISSUE TITLE
Removing and replacing message attachments does not work

### ISSUE THREAD

**Issue by Vampire** [Javacord/Javacord#933]
There is currently no way to remove or replace message attachments.
You can just add additional attachments.
This includes normal messages, interaction responses, and also ephemeral interaction responses.

Also the `Message` instance you for example get from `org.javacord.api.interaction.callback.InteractionOriginalResponseUpdater#update` or from `org.javacord.api.interaction.callback.InteractionMessageBuilder#editOriginalResponse` do not contain any attachments while the JSON sent from Discord does contain the attachments.

It should be able to
- remove all attachments
- remove or retain specific attachments
- add new attachments
- comibnations of the above

Related and maybe fixable with this too,
If you sent a message with an embed that needed an attachment being uploaded and then edit the message to contain an embed without a reference to that attachment, the attachment is currently shown as separate attachment to the message as the embed does not refer to it anymore, but it should actually be deleted automatically with the edit call.

**Comment by KILLEliteMaste** [comment]
Will be possible when we upgrade to gateway v10 #960 

> Existing attachments must be specified when PATCHing messages with new attachments. Any attachments not specified will be removed and replaced with the specified list

**Comment by Vampire** [comment]
I use a patched version of `MessageBuilderBaseDelegateImpl` for the project where I needed it, and it works like a breeze.
I'm just not sure whehter it affects something else and am not really familiar with that code, so I just used it locally for that project where I know it does what I need and everything else I need works.

**Comment by Vampire** [comment]
The changes I made are just
![grafik](https://user-images.githubusercontent.com/325196/171665967-d9f00e72-5859-4643-9a02-ee37c3b44cbe.png)

**Comment by Vampire** [comment]
But at least now you can use `removeExistingAttachments()` as work-around instead of a modified core class :-)

**Comment by KILLEliteMaste** [comment]
> But at least now you can use `removeExistingAttachments()` as work-around instead of a modified core class :-)

We are getting closer :)
