### ISSUE TITLE
[Suggestion] Support for creating and managing server "Events"

### ISSUE THREAD

**Issue by Macintosh-Fan** [Javacord/Javacord#946]
Add support so we can create, edit, delete, and start events?
![image](https://user-images.githubusercontent.com/50642934/150447487-e67df893-4db8-4901-9dd3-bedefd599663.png)

**Comment by AhmedA1559** [comment]
I'd like to be assigned to this.

**Comment by AhmedA1559** [comment]
Groundwork

- [ ] Implement Entities
- [ ] Deserialization
- [ ] Getters (by Id / by Name)
- [ ] Caching behavior

Events
- [ ] Event Create 
- [ ] Event modify
- [ ] Event Delete
- [ ] Event Status update

**Comment by Macintosh-Fan** [comment]
Glad it's done :)
