### ISSUE TITLE
Implement Attachment Option Type for Slash Interactions

### ISSUE THREAD

**Issue by Saladoc** [Javacord/Javacord#958]
See https://discord.com/developers/docs/interactions/application-commands#application-command-object-application-command-option-type

**Comment by RealYusufIsmail** [comment]
I will do this

**Comment by ShindouMihou** [comment]
I'll take over this issue since it has been stale for quite some time with the last person having not added the last change since a month ago. 🌮

**Comment by Saladoc** [comment]
> I'll take over this issue since it has been stale for quite some time with the last person having not added the last change since a month ago. 🌮

Thanks a lot, I'm still struggling to find time to contribute.
