### ISSUE TITLE
Upgrade to gateway version `10`

### ISSUE THREAD

**Issue by KILLEliteMaste** [Javacord/Javacord#960]
https://github.com/discord/discord-api-docs/discussions/4510

**Comment by RealYusufIsmail** [comment]
Will do this.

**Comment by RealYusufIsmail** [comment]
Can someone take over. I am too busy for this.

**Comment by RealYusufIsmail** [comment]
Might be able to work on this now

**Comment by RealYusufIsmail** [comment]
Almost done
