### ISSUE TITLE
Add missing Permission Types

### ISSUE THREAD

**Issue by Maddox3306** [Javacord/Javacord#964]
Please add a Permission Type for "Manage Permissions" in a Channel!

**Comment by Vampire** [comment]
We follow the naming of the API here, which is different from the naming in the UI.
Quote from the Discord API docs:
> Note that these internal permission names may be referred to differently by the Discord client. For example, "Manage Permissions" refers to MANAGE_ROLES, "Use Voice Activity" refers to USE_VAD, and "Timeout Members" refers to MODERATE_MEMBERS.
