### ISSUE TITLE
Implement the `GET/guilds/{guild.id}/bans/{user.id}` endpoint

### ISSUE THREAD

**Issue by wasdennnoch** [Javacord/Javacord#969]
This API endpoint to fetch a singular ban (as opposed to the entire ban list) does not currently seem to be implemented in Javacord as far as I can tell.  
This would be especially helpful in situations where you, for example, only want to know if a single user is banned - fetching the entire list to find a single user is overkill. Plus, on servers with big ban lists (tens or hundreds of thousands), fetching all bans often fails with a request timeout.

I am not yet familiar with the internals of Javacord, so unfortunately I can't easily create a PR for this myself right now. If this endpoint is implemented, these few lines should probably also be refactored to make use of it:
https://github.com/Javacord/Javacord/blob/0eed31c2ce38cfd2c60af6bb82c6cdc61caff954/javacord-core/src/main/java/org/javacord/core/event/server/member/ServerMemberBanEventImpl.java#L32-L35

Ref: https://discord.com/developers/docs/resources/guild#get-guild-ban

**Comment by AyuAi** [comment]
To add some external context, this is looking necessary for Beemo moving forward. As ban lists are getting bigger and bigger, Discord is no longer able to properly return the full list, making it impossible to see who is and is not banned using Javacord without a single-user ban endpoint.

Will probably try a PR myself later if I have the time/energy/(ability lol)
