### ISSUE TITLE
Next version finished notification

### ISSUE THREAD

**Issue by AffectedArc07** [Javacord/Javacord#982]
Can this issue be added to the next version milestone and be closed when the next version is out so we have an easy notification for when the next version is done?

This issue can then be used as an easy subscribe point without endless nagging, since (I assume) a lot of us are waiting on timeout support.

**Comment by Vampire** [comment]
Just use the GitHub watch functionality?
You can even select to just being notified if a release is created.

**Comment by AffectedArc07** [comment]
> Just use the GitHub watch functionality? You can even select to just being notified if a release is created.

I would rather not have my inbox flooded even further with the amount of projects I deal with, and would watch the milestone if I could. 
However, I will setup the release notification.

**Comment by Vampire** [comment]
You can anytime unwatch again if you are not interested in further releases anymore. :-)
I don't think you can somehow watch a milestone.
