### ISSUE TITLE
Component : TextInput

### ISSUE THREAD

**Issue by Alexiscomete** [Javacord/Javacord#998]
Hello,
It's my first issue in this project. I looked on closed and opened issues so I think it's not duplicated.

There is a **new** **Component** in Discord : **text input**
[Link to the documentation](https://discord.com/developers/docs/interactions/message-components#text-inputs)

**What it does :** allow bots to ask a short or long text input in a pop-up
So it's easier to ask something to users (now we must use a message listener and save channels and users)

**Comment by KILLEliteMaste** [comment]
Hey, this component has already been implemented with the Modals https://github.com/Javacord/Javacord/pull/962

**Comment by Alexiscomete** [comment]
Thanks, I don't search "modal". Sorry for this bad issue
